### ISSUE TITLE
Ace of Spades (224540) - reading access violation

### ISSUE THREAD

**Issue by vanyasem** [ValveSoftware/Proton#1313]
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: GTX 1080
- Driver/LLVM version: 396.54
- Kernel version: 4.18.5
- Link to full system information report as [Gist](https://gist.github.com/vanyasem/f787469ec8c50cdd3728340ef4c73269):
- Proton version: 3.7-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
```
2018-09-08 13:35:30+0300 [-] Starting MSAA Compatibility test
2018-09-08 13:35:30+0300 [-] Finished MSAA Compatibility test
2018-09-08 13:35:30+0300 [-] Loading images
2018-09-08 13:35:30+0300 [-] Setting texture quality
2018-09-08 13:35:30+0300 [-] Indexing images
2018-09-08 13:35:30+0300 [-] Starting loading screen...
2018-09-08 13:35:30+0300 [-] Traceback (most recent call last):
2018-09-08 13:35:30+0300 [-]   File "<string>", line 49, in <module>
2018-09-08 13:35:30+0300 [-]   File "C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\pyinstaller\PyInstaller\loader\pyi_importers.py", line 247, in load_module
2018-09-08 13:35:30+0300 [-]   File "C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\aoslib.run", line 300, in <module>
2018-09-08 13:35:30+0300 [-]   File "C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\aoslib.loadingscreen", line 33, in init
2018-09-08 13:35:30+0300 [-]   File "C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\aoslib.loadingscreen", line 88, in update_progress
2018-09-08 13:35:30+0300 [-]   File "C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\pyglet.window.win32", line 612, in dispatch_events
2018-09-08 13:35:30+0300 [-] WindowsError: exception: access violation reading 0x00000000
```
[steam-224540.log](https://github.com/ValveSoftware/Proton/files/2363225/steam-224540.log)

## Reproduction
1) Install the game
2) Launch it
3) Check game's log

**Comment by XakepSDK** [comment]
Same issue
