### ISSUE TITLE
 Penny Arcade's On the Rain-Slick Precipe of Darkness 3 (213030) 

### ISSUE THREAD

**Issue by veikk0** [ValveSoftware/Proton#2203]
# Compatibility Report
- Name of the game with compatibility issues: Penny Arcade's On the Rain-Slick Precipe of Darkness 3
- Steam AppID of the game: 213030

## System Information
- GPU: Intel 2nd Generation Core Integrated Graphics Controller (Intel® HD Graphics 3000) 
- Driver/LLVM version: Mesa 18.0.5
- Kernel version: 4.15.0-38-generic
- Link to full system information report: [system information](https://gist.github.com/veikk0/c86c34f6ac3c5ba433bfcaedc18484f5)
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game fails to start with no GUI error message. Proton log: [steam-213030.log](https://github.com/ValveSoftware/Proton/files/2735612/steam-213030.log)
Installing the latest winetricks and protontricks and using protontricks to fix .NET 4.0 and XNA 4.0 (command: protontricks 213030 xna40) allows the game to get to the "Zeboyd Games Presents" startup screen, after which it crashes. Fresh Proton log for an XNA-fixed game: [steam-213030-XNArepair.log](https://github.com/ValveSoftware/Proton/files/2735644/steam-213030-XNArepair.log)

## Reproduction
Download the game and attempt to run it.

## Other
The game's sequel, made by the same studio and presumably on the same engine, [works perfectly after re-installing XNA and fixing the .NET installation](https://github.com/ValveSoftware/Proton/issues/2202).

**Comment by kisak-valve** [comment]
`err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed` in the log points towards #18.

**Comment by Glog78** [comment]
kisak-valve the issue is most likely not XAudio2 -> After the intro screen the game tries to play a wmv video and i supose the videoplayer is not able to open the wmv files.

See also the error in the log after fixing xna (.net error)->

System.InvalidOperationException: An unexpected error has occurred.
   at Microsoft.Xna.Framework.Media.VideoPlayer.Play(Video video)
   at Rainslick3.Game1.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at Rainslick3.Program.Main(String[] args)

btw the same issue(s) might prevent Breath of Death VII to be run throu proton (xna + wmv video).

**Comment by flibitijibibo** [comment]
This game should work with 4.2-3 after using this script in the game directory:

https://gist.github.com/flibitijibibo/c97bc14aab04b1277d8ef5e97fc9aeff
