### ISSUE TITLE
Subnautica: Below Zero (848450)

### ISSUE THREAD

**Issue by im-0** [ValveSoftware/Proton#2286]
# Compatibility Report
- Name of the game with compatibility issues: Subnautica: Below Zero
- Steam AppID of the game: 848450

## System Information
- GPU: [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X] [1002:6798]
- Driver/LLVM version: mesa-vulkan-drivers-19.0.0-0.8.git.a920979d4f3.fc29.x86_64, xorg-x11-drv-amdgpu-18.1.99-0.16.git9045fb3.fc29.x86_64 (amdgpu, radv)
- Kernel version: 4.20.4
- Link to full system information report as [Gist](https://gist.github.com/): [steam-system-info-2019.01.31.txt ](https://gist.github.com/im-0/7454019084343af6c85dae0fe769fae1)
- Proton version: 3.16-6 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Game does not start at all when trying to launch from Steam.

## Reproduction
Try to launch Subnautica: Below Zero from Steam.

## Steam log and circumvention for this issue
When trying to launch the game from Steam, following appears on terminal:

```
>>> Adding process 5841 for game ID 848450
Traceback (most recent call last):
  File "/home/im/.local/share/Steam/steamapps/common/Proton 3.16 Beta/proton", line 309, in <module>
    shutil.copy(basedir + "/dist/lib/wine/dxvk/openvr_api_dxvk.dll", prefix + "/drive_c/windows/syswow64/")
  File "/usr/lib64/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/home/im/.local/share/Steam/steamapps/compatdata/848450/pfx//drive_c/windows/syswow64/'
Game removed: AppID 848450 "", ProcID 5840 
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
```

After creating the mentioned directory manually (`mkdir ~/.local/share/Steam/steamapps/compatdata/848450/pfx//drive_c/windows/syswow64/`), it proceeds a bit further:

```
>>> Adding process 9888 for game ID 848450
Traceback (most recent call last):
  File "/home/im/.local/share/Steam/steamapps/common/Proton 3.16 Beta/proton", line 310, in <module>
    shutil.copy(basedir + "/dist/lib64/wine/dxvk/openvr_api_dxvk.dll", prefix + "/drive_c/windows/system32/")
  File "/usr/lib64/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/home/im/.local/share/Steam/steamapps/compatdata/848450/pfx//drive_c/windows/system32/'
Game removed: AppID 848450 "", ProcID 9887 
```

After creating another directory (`mkdir ~/.local/share/Steam/steamapps/compatdata/848450/pfx//drive_c/windows/system32/`), game starts normally and becomes playable.

**Comment by nsivov** [comment]
@im-0, does any other game start for you when using Proton? Subnautica: Below Zero starts fine for me without manually creating directories on Ubuntu 18.04. Maybe it's indeed some python or python module issue in your case.

P.S. just making sure, you are not using custom Proton builds, are you?

**Comment by im-0** [comment]
@nsivov,

> does any other game start for you when using Proton?

Yes.

> P.S. just making sure, you are not using custom Proton builds, are you?

I have custom Proton build (which contains patch that fixes mouse problems in original Subnautica). So I tried both my custom build and latest official Proton version from Steam (do not actually remember in which order). Both attempts failed with the same errors.

So it is possible that my build was the first one, and it did something wrong inside the game's wineprefix.

**Comment by mercertom** [comment]
Same problem w America's Army, appeared overnight.

**Comment by kkarhan** [comment]
I've got similar issues:

## System Information
OS: Ubuntu 22.04.1 LTS x86_64 
Host: HP Z600 Workstation
Kernel: 5.15.0-48-generic 
Shell: bash 5.1.16
Resolution: 1920x1080
DE: GNOME 42.4
WM: Mutter
WM Theme: Adwaita
CPU: 2x Intel Xeon X5550 (16) @ 2.661GHz
GPU: NVIDIA GeForce GTX 1050 Ti [nvidia-515 & nvidia-470 tested]
Memory: 24 GiB
Proton version: experimental, 7.0-4, 6.3-8 & 5.0 tested
[System Specs](https://gist.github.com/kkarhan/39f17192407a963a431b9d91975b5747#file-system-specs-txt)
[Steam System Info](https://gist.github.com/kkarhan/39f17192407a963a431b9d91975b5747#file-steam-system-info-log)

## Symptoms
Subnautica: Below Zero silently crashes [UnityCrashHandler pops up almost instantly in btop, but nothing is shown on screen.]
Tested with the last 4 Proton versions.

## Reproduction
Starting Subnautica with [all known workarounds](https://www.protondb.com/app/848450) yielded only crashing Unity, as the [debug log](https://gist.github.com/kkarhan/39f17192407a963a431b9d91975b5747#file-debug-log) shows.

Oddly only the "legacy" build seems to run with Proton 7.0-4 & "-force-glcore" option but that's [over a year old](https://twitter.com/k3vk4/status/1576018203977056256)...

All the files can be found here:
https://gist.github.com/kkarhan/39f17192407a963a431b9d91975b5747

**Comment by kkarhan** [comment]
Also the orgininal "Subnautica" just runs flawlessly out of the box.

**Comment by MollyMaclachlan** [comment]
I've been experiencing audio crackling with Subnautica: Below Zero.

## System Information

- Distrobution: Slackware -current
- Kernel: 6.12.62
- CPU: AMD Ryzen 7 3800X (16) @ 4.5GHz
- GPU: AMD 4X 6600 (8GB VRAM)
- Motherboard: ASUS B550-F
- RAM: 32GB
- Using Pipewire 1.4.9 for audio
- [Full system info](https://gist.github.com/MollyMaclachlan/bda1a38e3bc9117664d4e05d0c6d6e16)

## Symptoms

Intermitten audio crackling. It comes and goes, usually over longer stretches (periods of 10 minutes or more). I don't think I've got it on the title menu; specifically in-game.

It's not terribly loud or hugely intrusive, and doesn't seem to be bothering my viewers after a few streams with it, but it does annoy me. It's usually most notable when it happens over a voice line or background music.

I did not get this issue with the original Subnautica, which ran perfectly out of the box. I haven't had any other issues with Below Zero (no lag, crash, etc.)

[Log from my last session](https://gist.github.com/MollyMaclachlan/42f77aa49843b0209f99ccfdb1019407); I used Proton Experimental for this one, but I also did a session with 9.0-4 and had the same audio crackling.

## Reproduction

Load Subnautica: Below Zero and play for a while.
