### ISSUE TITLE
Heroes of Might and Magic V (15170)

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/Proton#2401]
- GTX 960 driver v418..43
- Kernel version: 4.18
- Proton version: 3.16-8 Beta
- Ubuntu 18.10

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Game launches in small black window. I hear music, but doesn't seem to come up. Also, it minimizes right away, and the black square is when I try to bring it back up.

Sometimes when I get into the game it looks okay but runs really choppy.

**Comment by kisak-valve** [comment]
Hello @BloodyIron, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by BloodyIron** [comment]
Gist here: https://gist.github.com/BloodyIron/7618e6e61f90d477164321b78011c9c5

Working on log next.

**Comment by BloodyIron** [comment]
For some reason the log file every time is over 40MB, so i threw it up on a share server I run : https://dewey.lanified.com/s/k9iMRoHqWT9kRfs

That link has a lifespan of just under 3 days. So please download it before it expires! Expiration is just under 3 days from when this post was made. Sorry future internet!

**Comment by kisak-valve** [comment]
You should be able to throw the log into an archive to get it down to a reasonable size that github will accept directly.

**Comment by BloodyIron** [comment]
I don't even know why I didn't think of compressing basic text, HAH! Let me do that.

**Comment by BloodyIron** [comment]
[steam-15170.zip](https://github.com/ValveSoftware/Proton/files/2950746/steam-15170.zip)

**Comment by kisak-valve** [comment]
Looks like the log has a bunch of these:
```
9736.266:0008:0009:err:x11settings:X11DRV_ChangeDisplaySettingsEx No matching mode found: width=32 height=32 bpp=32 freq=60 (NoRes)
9736.266:0008:0009:err:x11settings:X11DRV_ChangeDisplaySettingsEx No matching mode found: width=32 height=32 bpp=32 (NoRes)
```

**Comment by zzhiyi** [comment]
Try alt+tab to and away from the game can work around this. It's strange that it will switch to a 32x32 resolution.

**Comment by BloodyIron** [comment]
I had tried alt tabbing a bunch, did not improve the situation at all.

**Comment by zzhiyi** [comment]
I tested the alt tabbing on Ubuntu 18.10 with xorg. What distro are you running? There is something wrong with the window events handling I haven't figure out the exact cause yet.

**Comment by BloodyIron** [comment]
Hmmm thought I mentioned Ubuntu 18.10 in my OP, sorry for missing that! Yeah, 18.10 xorg.

**Comment by artemyto** [comment]
To avoid the black screen issue you can enable virtual desktop in game's prefix. You can do it that way:
1. run in terminal WINEPREFIX=/path/to/steamdir/steamapps/compatdata/15370/pfx winecfg
2. open Graphics tab, check Emulate virtual desktop, set desktop size

I tried the game with d9vk, it worked good. The only one issue I found is camera zoom problem, but you can solve it by using PageUp/PageDown keys or by changing the Camera mode in game's options from 'Normal' to 'Vertical fixed' or 'Classic HOMM view'.

**Comment by friedc** [comment]
Doesn't work with or without virtual desktop in `proton-6.3-6c`. The game can't be started by pressing "Play". The log is very short and holds the following lines:

```
======================
Proton: 1629748146 proton-6.3-6c
SteamGameId: 15170
Command: ['/media/gamedisk/steamlibrary/steamapps/common/Heroes of Might and Magic 5/bin/H5_Game.exe']
Options: {'forcelgadd'}
depot: 0.20210723.18
pressure-vessel: 0.20210722.0
scripts: v0.20210722.0-0-gb142f90
soldier: 0.20210719.0 soldier 0.20210719.0
======================
```

**Comment by kisak-valve** [comment]
Hello @friedc, can you completely close Steam, then run `steam` from a terminal and check if there's a python error coming from Proton in the terminal spew when you try to run the game?

**Comment by friedc** [comment]
> Hello @friedc, can you completely close Steam, then run `steam` from a terminal and check if there's a python error coming from Proton in the terminal spew when you try to run the game?

The terminal shows the following messages after the startup of steam:

```
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/REDACTED/.steam/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-08-24 18:49:00] Startup - updater built Aug 20 2021 20:39:20
[2021-08-24 18:49:00] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
[2021-08-24 18:49:00] Loading cached metrics from disk (/home/REDACTED/.steam/package/steam_client_metrics.bin)
[2021-08-24 18:49:00] Using the following download hosts for Public, Realm steamglobal
[2021-08-24 18:49:00] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-08-24 18:49:00] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-08-24 18:49:00] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2021-08-24 18:49:00] Verifying installation...
[2021-08-24 18:49:00] Verification complete
STEAM_RUNTIME_HEAVY: /home/REDACTED/.steam/ubuntu12_64/steam-runtime-heavy
```
There are no additional messages printed when I press "Play".

**Comment by kisak-valve** [comment]
The distro-modified Steam package you're using might have intercepted some of the terminal spew and put it in error.log (maybe `~/.steam/steam/error.log`?). Can you check of that log file exists and has a hint?

**Comment by friedc** [comment]
> The distro-modified Steam package you're using might have intercepted some of the terminal spew and put it in error.log (maybe ~/.steam/steam/error.log?). Can you check of that log file exists and has a hint?

I found the file in ~~the place you mentioned~~ `~/.steam/error.log`. Here are the relevant lines:

```
GameAction [AppID 15170, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Proton: Upgrading prefix from 4.11-2 to 6.3-3 (/home/REDACTED/.steam/steam/steamapps/compatdata/15170/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 1264, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 1078, in init_session
    g_compatdata.setup_prefix()
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 714, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 540, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/REDACTED/.steam/steam/steamapps/compatdata/15170/tracked_files'
GameAction [AppID 15170, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 15170, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 15170, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 15170, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/REDACTED/.steam/ubuntu12_32/reaper SteamLaunch AppId=15170 -- '/home/REDACTED/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/media/gamedisk/steamlibrary/steamapps/common/Heroes of Might and Magic 5/bin/H5_Game.exe'\0
Game update: AppID 15170 "", ProcID 15958, IP 0.0.0.0:0
Starting app 15170
>>> Adding process 15958 for game ID 15170
GameAction [AppID 15170, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 15170, ActionID 1] : LaunchApp changed task to Completed with ""
Installing breakpad exception handler for appid(steam)/version(1629497411)
ERROR: ld.so: object '/home/REDACTED/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/REDACTED/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/REDACTED/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/REDACTED/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/REDACTED/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 15964 != 15961, skipping destruction (fork without exec?)
>>> Adding process 15960 for game ID 15170
>>> Adding process 15961 for game ID 15170
>>> Adding process 15962 for game ID 15170
Proton: Upgrading prefix from 4.11-2 to 6.3-3 (/home/REDACTED/.steam/steam/steamapps/compatdata/15170/)
Proton: Removing ShellExecute DDE registry entries.
>>> Adding process 16250 for game ID 15170
Traceback (most recent call last):
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 1264, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 1078, in init_session
    g_compatdata.setup_prefix()
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 714, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/media/gamedisk/steamlibrary/steamapps/common/Proton 6.3/proton", line 540, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/REDACTED/.steam/steam/steamapps/compatdata/15170/tracked_files'
Game removed: AppID 15170 "", ProcID 15958
Uploaded AppInterfaceStats to Steam
Exiting app 15170
```

**Comment by friedc** [comment]
I deleted the prefix in `~/.steam/steam/steamapps/compatdata/15170` and let steam recreate it. Now the game runs (after a bit of Alt-tabbing) but only a small portion of the screen is shown.
![Screenshot_2021-08-24_20-10-41](https://user-images.githubusercontent.com/52925889/130668091-60a1eb3d-b12b-41dd-b691-64d8da87647c.png)

The log looks way more interesting now. [steam-15170.log](https://github.com/ValveSoftware/Proton/files/7041322/steam-15170.log)

**Comment by leillo1975** [comment]
I can't play this game. I boutght it because in protondb is listed as a working game. I have the following error after pressing start:
![Captura de pantalla de 2022-03-12 17-43-50](https://user-images.githubusercontent.com/551821/158026871-5a14407a-69b4-4b93-b59b-63ff40aeb851.png)
I tried with proton 7.0 and 6.3-8 with the same results. This is the log:
[steam-15170.log](https://github.com/ValveSoftware/Proton/files/8237976/steam-15170.log)

**Comment by friedc** [comment]
@leillo1975
Can you see any part of the video on startup? 

For me it runs. I used proton 7.0-1 and Alt-Tabbed to the video on startup. Then I pressed enter to go into the main menu of the game. I am on `Ubuntu 20.04.4 LTS` with a radeon RX 480 graphics card using Xorg with a resolution of 3840x2160.

The game can be a bit finnicky and requires Alt-tabbing on startup.

Edit: Here is my log
[steam-15170.log](https://github.com/ValveSoftware/Proton/files/8238144/steam-15170.log)

**Comment by leillo1975** [comment]
I can´t see nothing, only the error popup

**Comment by friedc** [comment]
@leillo1975 
Could it be a problem with the game files (what is the filesystem? have you verified the game files?)? I ask this, because when searching for "application load error 2:0000065558" I found this:

https://steamcommunity.com/app/15200/discussions/0/540734423766558560/

**Comment by leillo1975** [comment]
I verified the files, and I uninstalled and installed it again, but the problem persists. My filesystem is EXT4

**Comment by friedc** [comment]
@leillo1975 
I see the following lines in my log that have no equivalent entries in your log:

```
22413.836:013c:0140:trace:loaddll:build_module Loaded L"Z:\\media\\gamedisk\\steamlibrary\\steamapps\\common\\Steam.dll" at 02AC0000: native
22413.850:013c:0140:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\lsteamclient.dll" at F5E80000: builtin  
22413.850:013c:0140:trace:loaddll:build_module Loaded L"C:\\Program Files (x86)\\Steam\\steamclient.dll" at 38000000: native
22413.885:013c:0140:trace:loaddll:free_modref Unloaded module L"C:\\Program Files (x86)\\Steam\\steamclient.dll" : native
22413.903:013c:0140:trace:loaddll:free_modref Unloaded module L"Z:\\media\\gamedisk\\steamlibrary\\steamapps\\common\\Steam.dll" : native
```

Could you try to delete the wine prefix and let Steam recreate it? For me this was in `~/.steam/steam/steamapps/compatdata/15170`

**Comment by friedc** [comment]
* Works on experimental-bleeding-edge with *PROTON_USE_WINED3D=1* with the following caveat: When I start the game I cannot move the mouse across the whole screen. I have to change the resolution to 1920x1080 and then back to 3840x2160 to fix this. Also I have to use a software mouse cursor. [steam-15170.log](https://github.com/ValveSoftware/Proton/files/9283674/steam-15170.log)
* Does not work on experimental-bleeding-edge with default settings. It complains that "directx9 can not be initialized" .I don't have mesa 22 yet and dxvk does not like that. [steam-15170.log](https://github.com/ValveSoftware/Proton/files/9283684/steam-15170.log)
* Does not work on proton-7.0-4-rc3 with default settings. Does not start. [steam-15170.log](https://github.com/ValveSoftware/Proton/files/9283715/steam-15170.log)
* Does not work on proton-7.0-4-rc3 with *PROTON_USE_WINED3D=1*. It starts but shows a black window. [steam-15170.log](https://github.com/ValveSoftware/Proton/files/9283717/steam-15170.log)

**Comment by zskamljic** [comment]
I have tried running with instructions on protondb, with results that are hard to reproduce, it seems in some cases when deleting the prefix I'm able to get in the game and change the settings, but then after restarting the app I either get a normal experience or the game opens the black window and crashes after playing the ubisoft intro video (only audio is present, screen remains blank), I have also tried to remove intro videos in hopes of resolving this, but had no success.
Here's the log for stock proton prefix:  [steam-15370-default.log](https://github.com/ValveSoftware/Proton/files/9461862/steam-15370-default.log)
An attempt with emulating desktop: [steam-15370-emulate-desktop.log](https://github.com/ValveSoftware/Proton/files/9461865/steam-15370-emulate-desktop.log)

FWIW, I think there might be more than one process, as it seems like virtual desktop appears, dissappears and re-appears. I'm unsure exactly what's wrong, but virtual desktops seem to be showing solid color at all times - not even a window shows up, and trying `protontricks 15370 winecfg` opens the desktop, with the same problem - solid color, with nothing drawn.

**Comment by friedc** [comment]
Can't get this game to start anymore. No version of proton works. It doesn't show any window and it doesn't produce any logs (not even the mentioned `~/.steam/error.log`). I am now on Ubuntu 22.04 LTS. Could this be the reason?

**Comment by Deleetdk** [comment]
When I launch the game, it starts in the menu bar. If I click it, the mouse is inside the game and I can skip the intro videos. However, the game remains minimized. Alt-tab etc. is disabled. I can't click anything, nothing responds but the computer is not frozen (num lock works). The only way out is to switch to a terminal (ctrl+alt+1) then kill all the relevant processes. The log file is huge.

[steam-15170.log.zip](https://github.com/ValveSoftware/Proton/files/13678499/steam-15170.log.zip)

Mostly it's this part repeated:

```
info:  Device reset
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              4876
info:      - Height:             2880
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:      - Swap effect:        1
info:  Setting display mode: 4876x2880@60
info:  Setting display mode: 4876x2880@60
217135.282:012c:0130:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
217135.282:012c:0130:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
warn:  Device reset failed: Device not reset
217135.283:012c:0130:err:x11drv:xinerama_get_fullscreen_monitors Failed to get xinerama fullscreen monitor indices.
217135.283:012c:0130:err:x11drv:update_net_wm_fullscreen_monitors Failed to find xinerama monitors at (0,0)-(4876,2880)
217135.283:012c:0130:err:x11drv:xinerama_get_fullscreen_monitors Failed to get xinerama fullscreen monitor indices.
217135.283:012c:0130:err:x11drv:update_net_wm_fullscreen_monitors Failed to find xinerama monitors at (0,0)-(4876,2880)
info:  Device reset
```

Some kind of high resolution and D9 error.

I've tried with `PROTON_LOG=1 %command%` and without, no difference. Running latest Proton in Steam on Mint 21.2. GPU is AMD 6650 XT with kisak mesa drivers.

I've been unable to force the game to start in windowed mode following the instructions here. https://www.protondb.com/app/15170 Is there a way to force windowed mode?
