### ISSUE TITLE
Interstellar Rift (363360)

### ISSUE THREAD

**Issue by 7thCore** [ValveSoftware/Proton#2522]
# Compatibility Report
- Name of the game with compatibility issues: Interstellar Rift
- Steam AppID of the game: 363360
- Log: [steam-363360.log](https://github.com/ValveSoftware/Proton/files/3060424/steam-363360.log)

## System Information
- GPU: RX 580
- Driver/LLVM version: mesa: 19.0.1-2
- Kernel version: 5.0.5-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/7thCore/d9923eaebb81c600b8aa4f84cfca2d2e

- Proton version: 4.2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
The game runs but throws out an error only on AMD cards. Nvidia cards work fine (Tested on my laptop with an 630M)
Error reads:
The driver for your AMD RADV POLARIS10 (LLVM 8.0.0) are over a year old, consider updating them. It might fix chrashes like this one.

## Reproduction
Install vcrun2015, corefonts, dotnet472 with winetricks and try to run the game with proton and the system having an AMD gpu.

If need be i can upload my proton prefix with working 4.7.2 .NET.

**Comment by 7thCore** [comment]
I would also like to add that i have tried running the steam-runtime and steam-native with the latest libraries installed. Also i have all the amd vulkan and opengl  libraries and packages installed. I also tried to run the game with the amdvlk package and the end result was the same: error about outdated drivers.

**Comment by ghost** [comment]
Hi @7thCore after installing the amdvlk package... do you have started your game with that launch- parameter? `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json %command%` because if you haven't removed vulkan-radeon before, vulkan still use mesa.

**Comment by 7thCore** [comment]
Hi @Alexander88207, no i did not do it in that order. I opened a terminal and executed the following comand: export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd64.json"
Then i started steam from the same terminal windows and after that the game.

The export command should pass the enviroment variable to steam and proton should it not?

**Comment by ghost** [comment]
Not really. If you still got that error message with AMD RADV POLARIS10 (LLVM 8.0.0)  then it was not amdvlk because amdvlk uses the right gpu name for example AMD RX 570 Series.

**Comment by 7thCore** [comment]
I have tried your suggestion. The only diffrence it made is that instead of the AMD RADV POLARIS10 (LLVM 8.0.0) name it said VideoController1

Edit: it is the same error i got when i tried the export through terminal way.

**Comment by ghost** [comment]
Alright, thanks for testing :+1:

**Comment by 7thCore** [comment]
I have another piece of information for the driver problem i'm having. While asking on the official steam forum of the game, one of the players asked me if the game server could run in linux so i started tinkering with that. I basicly used steam and in the startup arguments typed %command% -server. The console opened up and the server started running.

And then i've seen this:

`
Game Version: 0.2.7.21
Arguments: -splashscreen -server
Renderer debug flags: RDF_None
OS: Microsoft Windows 7 Professional (6.1.7601.65536) 64-bit 
CPU:

    Index: 0
    Name: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
    Manufacturer: Genuinelntel
    Description: Inte164 Family 6 Model 45 Stepping 7 
    AdressWidth: 64
    Core Count: 6 / N/A
    ThreadCount: N/A
    Current Clock Speed: 2712 MHz
    Current Voltage: N/A V

RAM: 18.35 GB / 31.42 GB
Virtual: 0.00 GB / 4.00 GB
HDD: [Z:\] 62.03 GB / 118.68 GB (52% free): Fixed NTFS 
GPU:
    {
    Index: 0
    Name: AMD RADV POLARIS10 (LLVM 8.0.0) 
    Driver Version: 1.0
    Driver Date: 2017-01-01
    Video Mode: 1920 x 1080 x 4294967296 colors
    }
Display:
    {
    Index: 0
    Name:
    Resolution: 1920x1080x32 bpp @ 60 Hz
    Position: (X: 0, V: 0) 
    Orientation: Landscape
    }
    {
    Index: 1
    Name:
    Resolution: 1920x1080x32 bpp @ 60 Hz
    Position: (X: 0, V: 0) 
    Orientation: Landscape
    }
`

Notice the driver version and date?

**Comment by 7thCore** [comment]
I have some new information from the developers. They ware nice enough to check some dump files from my attempts.

Here is what they told me:

```
The pointer to glBindVertexArray is null
which is why it crashes
So, I think on AMD on Linux GLEW somehow doesn't get the correct function pointers
There are a few gl calls before that glBindVertexArray, but those were already in OpenGL before version 3
```
Game uses OpenGL 3.3

**Comment by ananace** [comment]
Decided to have a go at testing this game out as well, to see if I can be of help in the debugging. Noticed something interesting in the console output when starting it up;

```
>>> Adding process 2266 for game ID 363360
22:31:36,093 [Game.Configuration.ServerConfig] {Gamelogic} (Ananace) INFO: Loading server config file: server.json 
22:31:37,820 [Game.Framework.Engine] {Main} (Ananace) INFO: Creating window. Size: 1920x1080, Position: (X: 0, Y: 0), Fullscreen: True 
22:31:37,869 [Game.Framework.DisplayHelpers] {Main} (Ananace) INFO: Changing display to fullscreen mode.
        GDI Name: \\.\DISPLAY1
        Name: 
        Resolution: 1920x1080x32 bpp @ 60 Hz
        dmFields: BitsPerPixel, PixelsWidth, PixelsHeight, DisplayFlags, DisplayFrequency
        dmFixedOutput: DMDFO_DEFAULT
        dmDisplayFlags: DMDM_DEFAULT 
22:31:37,870 [Aluna] {Aluna} (Ananace) INFO: glGetString(GL_RENDERER): Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.6.0-sabayon, LLVM 10.0.1) 
22:31:37,871 [Aluna] {Aluna} (Ananace) INFO: glGetString(GL_VENDOR): X.Org 
22:31:37,871 [Aluna] {Aluna} (Ananace) INFO: glGetString(GL_VERSION): 4.6 (Compatibility Profile) Mesa 20.1.5 
22:31:37,871 [Aluna] {Aluna} (Ananace) INFO: Selected OpenGL version 4.6 
Error initializing GLEW: Missing GL version
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Aluna.AlunaNETBridgePINVOKE.Draw_Create(HandleRef jarg1)
   at Aluna.Draw.Create(CRenderer renderer)
   at Game.Framework.Engine.i_InitializeResources()
   at Game.Framework.Engine.Initialize(String windowTitle, Int32 startX, Int32 startY, Int32 width, Int32 height, InitializeFlags initFlags, Int32 screenId, Int32 screenRefreshRate, RendererInitFlags rendererInitFlags, Single frameRateLimit, TextureFilteringMode textureFilteringMode, Single anisotropicLevel)
   at Game.Program.InitEngine(InitializeFlags flags)
   at Game.Program.InitClient(String launchDetails)
   at Game.Program.Init()
   at Game.Program.Main(String[] args)
22:31:37,909 [Game.Framework.DisplayHelpers] {Main} (Ananace) INFO: Resetting display mode for screen: 0 
wine: Unhandled page fault on read access to 00000000 at address 00000000 (thread 00d0), starting debugger...
```

The GLEW error sounds very suspect.

**Comment by 7thCore** [comment]
I had a back and forth with the devs of the game with this for quite a while. Sending dump files, crash logs, installing different versions of GLEW and using steam native. None of it worked. I even asked them if they had experimental openGL features enabled (because this was a solution for another game) and they had it on from the get go. No luck yet

**Comment by JulianGro** [comment]
Game runs on Nvidia proprietary with dotnet472 installed via Protontricks on Proton 5.0-10. (vcrun2012 and corefonts are also installed, but I am not sure if they are needed as vcrun2012 should get installed automatically on first launch and corefonts should already be installed)
I couldn't easily get higher Proton version to work since dotnet472 and/or older dependencies are broken and disabled in winetricks.

There is problems with the networking. The server list does not load and when you are on a server you can get very bad lag, bad enough that I would call it unplayable. Otherwise performance is absolutely fine.

**Comment by 7thCore** [comment]
@JulianGro use the -nossl argument. The server list is empty because it uses ssl to access the master server and it dosen't work with wine. With -nossl in the arguments field on steam your server list should be populated.

**Comment by Teddy-Kun** [comment]
I cannot get the game to work at all. I have tried different versions of Proton (both official builds and various GE versions). I have tried installing dotnet472 and vcrun2012 as well as different version of said libraries without success. I always got errors that lead me to believe, that something is wrong with my mono installation. Then today with the newest Proton-GE-48 something changed. Now I get a different error. I will paste the log below, but I think the interesting parts are the following:

```
1661.102:0124:0128:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
[...]
at Game.Program:Main <0x0028a>
at <Module>:runtime_invoke_void_object <0x000af>
[...]
1661.102:0124:0128:trace:seh:call_vectored_handlers handler at 0000000180103430 returned 0
```

full log: [steam-363360.log](https://github.com/ValveSoftware/Proton/files/10537689/steam-363360.log)

My system is:
Arch Linux
32GB of RAM
Ryzen 5800X3D
Radeon 7900XT with latest -git drivers

Any help or fixes would be appreciated.
