### ISSUE TITLE
Proton fails to launch, python error

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/Proton#3195]
It happens, for ex., when I play the game, close it, then try to play it again. Here's output in console when try Killing Floor 2:

```Loaded Config for Local Selection Path for App ID 232090, Controller 0: /home/xdshot/.local/share/Steam/steamapps/workshop/content/241100/1142017723/878622716265121877_legacy.bin
Loaded Config for Local Selection Path for App ID 232090, Controller 0: /home/xdshot/.local/share/Steam//controller_base/templates/controller_xboxone_gamepad_joystick.vdf
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
esync: up and running.
esync: up and running.
esync: up and running.
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 232090, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 232090, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 232090 "", ProcID 12320, IP 0.0.0.0:0
ERROR: ld.so: object '/home/xdshot/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 232090
Loaded Config for Local Selection Path for App ID 232090, Controller 0: /home/xdshot/.local/share/Steam/steamapps/workshop/content/241100/1142017723/878622716265121877_legacy.bin
Loaded Config for Local Selection Path for App ID 232090, Controller 0: /home/xdshot/.local/share/Steam//controller_base/templates/controller_xboxone_gamepad_joystick.vdf
>>> Adding process 12320 for game ID 232090
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/xdshot/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xdshot/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 232090, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 12321 for game ID 232090
ERROR: ld.so: object '/home/xdshot/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/xdshot/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Traceback (most recent call last):
  File "/home/xdshot/.local/share/Steam/steamapps/common/Proton 4.11/proton", line 709, in <module>
    g_session.init_session()
  File "/home/xdshot/.local/share/Steam/steamapps/common/Proton 4.11/proton", line 552, in init_session
    g_compatdata.setup_prefix()
  File "/home/xdshot/.local/share/Steam/steamapps/common/Proton 4.11/proton", line 393, in setup_prefix
    win_vr_config = subprocess.check_output([g_proton.wine_bin, "winepath", "-w", vr_config], env=g_session.env, stderr=g_session.log_file).decode("utf-8")
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/xdshot/.local/share/Steam/steamapps/common/Proton 4.11/dist/bin/wine', 'winepath', '-w', '/home/xdshot/.local/share/Steam/config']' returned non-zero exit status 1.
>>> Adding process 12322 for game ID 232090
Game removed: AppID 232090 "", ProcID 12320 
Uploaded AppInterfaceStats to Steam
Exiting app 232090
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.
```

I have to restart the steam to resolve it each time.

**Comment by xDShot** [comment]
#2573 probably related

**Comment by aeikum** [comment]
Do you have any launch options set for this game? Specifically, PROTON_NO_ESYNC? Or anything set in user_settings.py?

**Comment by xDShot** [comment]
Yes, KF2 has `PROTON_NO_ESYNC=1 %command% -nostartupmovies`. user_settings.py not changed.

**Comment by aeikum** [comment]
I think this is the same issue as #3191, then. Can you check if it's fixed in 4.11-8?

**Comment by xDShot** [comment]
Seems disappeared, thanks.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
