### ISSUE TITLE
Putt-Putt: Pep's Birthday Surprise (294700)

### ISSUE THREAD

**Issue by W73** [ValveSoftware/Proton#3281]
# Compatibility Report
- Name of the game with compatibility issues: Putt-Putt: Pep's Birthday Surprise
- Steam AppID of the game: 294700

## System Information
- GPU: Intel
- Driver/LLVM version:
- Kernel version: 5.11
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 4.1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
Found problem with Windows 7/8/10 solved by some Daemon Tools. 

- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Does not start. 
Found this in app directory . I think it is not related to Proton at all. 

```
cat Putt-Putt\ --\ Pep\'s\ Birthday\ Surprise.log
Attempting to create a 16-bit (5-6-5) software render target...
YAGA: Boot process
Processing boot script...
Getting global objects...
-- Total system memory: 2097151 KB --
-- Available system memory: 2097151 KB --
Traceback (most recent call last):
File "<string>", line 557, in ?
File "<string>", line 178, in BOOT_Main
File "C:\alienbrainWork\Putt7\Putt7_Game\code\globals.pyc", line 170, in Init
TypeError: argument 1 must be yagares.IResourceFormatHandler, not None
```

Seems to be easily solved. But i am not developer. 

## Reproduction
Run it.

**Comment by kisak-valve** [comment]
Hello @W73, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by W73** [comment]
Ok. I will try.

**Comment by W73** [comment]
[steam-294700.log](https://github.com/ValveSoftware/Proton/files/3931221/steam-294700.log)

Thanks. Daughter will be happy.

**Comment by kisak-valve** [comment]
Thanks, for easy reference, this game uses the [Yaga game engine](https://www.uvlist.net/groups/info/yagaengine) which is fairly rare with 5 releases between 2002-2003.

**Comment by aeikum** [comment]
Unfortunately this game seems to be broken on Windows, too, in the exact same way. Apparently the game requires your system to have a CD drive available, see this discussion: https://steamcommunity.com/app/294700/discussions/0/1642042464734212682/

You can actually work around this in Proton, and the game does launch and play! These steps worked for me:

1) Set your Steam launch options for this game to `PROTON_DUMP_DEBUG_COMMANDS=1 %command%`
2) Launch the game and let it fail.
3) In a Terminal, run `/tmp/proton_$USER/run winecfg`
4) In the configuration dialog that pops up, on the Drives tab, select "Add..." and choose drive `D:`.
5) Select drive `D:` in the dialog, choose "Show Advanced", change the Path to `/mnt` and change the Type to `CD-ROM`. See screenshot below.
6) Click OK.
7) The game should now work. You can now clear out the launch options dialog.

Give it a shot! Do note that some other users in the Steam community have reported other problems with the game on Windows. It appears to be pretty buggy :(

![Screenshot_2019-12-09_10-00-00](https://user-images.githubusercontent.com/34554541/70451293-b8f2d900-1a6a-11ea-9904-326f25a6b134.png)

**Comment by W73** [comment]
Thanks for hint, but i am not able to do find that /tmp on flatpak version of steam. 
I was able found that $HOME with steam-294700.log, but not /tmp. 
I will investigate that.

**Comment by aeikum** [comment]
Sorry, I have no idea how flatpak works. If you figure it out, I'd be interested to hear what happened.

**Comment by W73** [comment]
I am able to run winecfg utility via 
`$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Proton 4.11/dist/bin/wine64 winecfg ` i set it per image, but no success. 
I also tried Netherland Language version, it came with different cfg file, but it fails too.

**Comment by Hoff16** [comment]
FYI, I've had success with launching the game using GE-Proton10-32. Not sure what the fixes are that it performs but at least its a bit easier than making advanced Wine config changes.

**Comment by Hoff16** [comment]
FYI this is solved from a Protonfix in GE-Proton that creates the DOS Device (CD-ROM) drive in the game's prefix.

Link to protonfix:
https://github.com/Open-Wine-Components/umu-protonfixes/blob/master/gamefixes-steam/294700.py

Another Humongous Game has the exact same problem:

[Pajama Sam 4: Life Is Rough When You Lose Your Stuff!](https://github.com/ValveSoftware/Proton/issues/10015)

Thankfully it also now works via GE-Proton and the same protonfix applied to it.

**Comment by Hoff16** [comment]
@kisak-valve is this type of thing in-scope for the devs (Valve/CodeWeavers) to work on since this "bug/anti-cheatish" also exists on Windows?

**Comment by data-goblin** [comment]
Confirmed on Proton Experimental (11.0-100), Arch/Omarchy. The engine enumerates every drive letter looking for a CD-ROM and, finding none, passes `None` where a resource handler belongs, producing exactly this traceback. Adding a CD-ROM drive to the prefix fixes it: point `dosdevices/d:` at an *empty* directory and set `"d:"="cdrom"` under `[Software\Wine\Drives]` in `system.reg`. Pointing `d:` at the install directory instead makes it worse, since the game then resolves its own files through a read-only CD path and dies before it writes its log.

---
Written by Claude Opus 5 via Claude Code, verified by me on my machine.
