### ISSUE TITLE
Drinks With Abbey (1201870)

### ISSUE THREAD

**Issue by Simmonz** [ValveSoftware/Proton#3757]
I tried running Drinks With Abbey using Proton but it crashes at launch. The Steam AppID of the game is 1201870. I added PROTON_LOG=1 %command% to the game's launch and got the following log:

[steam-1201870.log](https://github.com/ValveSoftware/Proton/files/4465976/steam-1201870.log)

I have checked whether there are updates for my system available and I am up to date

System Information:

Distro: Manjaro

GPU: RX 5700 XT 8GB

Driver/LLVM version: Mesa 20.0.4/9.0.1

Kernel version: 5.6.3-2-MANJARO

Proton version: 5.0-5

https://gist.github.com/Simmonz/f8c7ce3dabb552707a00d44c5004602e

**Comment by kisak-valve** [comment]
These look like the lines of interest from the log:
```
512.751:0037:0038:err:module:import_dll Library SDL2_ttf.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\font.pyd") not found
512.755:0037:0038:err:module:import_dll Library libjpeg-62.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
512.758:0037:0038:err:module:import_dll Library libpng-3.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
512.760:0037:0038:err:module:import_dll Library SDL2_image.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
[...]
512.787:0037:0038:err:module:import_dll Library libpng-3.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\_renpy.pyd") not found
Could not import _renpy. Please ensure that this program has been built
and unpacked properly.

You may be using a system install of python. Please run Drinks-With-Abbey.sh,
Drinks-With-Abbey.exe, or Drinks-With-Abbey.app instead.

Traceback (most recent call last):
  File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\Drinks-With-Abbey.py", line 198, in <module>
    main()
  File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\Drinks-With-Abbey.py", line 195, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\renpy\bootstrap.py", line 277, in bootstrap
    import _renpy; _renpy
ImportError: DLL load failed: Module not found.
```

**Comment by Simmonz** [comment]
> These look like the lines of interest from the log:
> 
> ```
> 512.751:0037:0038:err:module:import_dll Library SDL2_ttf.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\font.pyd") not found
> 512.755:0037:0038:err:module:import_dll Library libjpeg-62.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
> 512.758:0037:0038:err:module:import_dll Library libpng-3.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
> 512.760:0037:0038:err:module:import_dll Library SDL2_image.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\pygame_sdl2\\image.pyd") not found
> [...]
> 512.787:0037:0038:err:module:import_dll Library libpng-3.dll (which is needed by L"Z:\\home\\matthew\\.local\\share\\Steam\\steamapps\\common\\Drinks With Abbey\\lib\\windows-i686\\lib\\_renpy.pyd") not found
> Could not import _renpy. Please ensure that this program has been built
> and unpacked properly.
> 
> You may be using a system install of python. Please run Drinks-With-Abbey.sh,
> Drinks-With-Abbey.exe, or Drinks-With-Abbey.app instead.
> 
> Traceback (most recent call last):
>   File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\Drinks-With-Abbey.py", line 198, in <module>
>     main()
>   File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\Drinks-With-Abbey.py", line 195, in main
>     renpy.bootstrap.bootstrap(renpy_base)
>   File "Z:\home\matthew\.local\share\Steam\steamapps\common\Drinks With Abbey\renpy\bootstrap.py", line 277, in bootstrap
>     import _renpy; _renpy
> ImportError: DLL load failed: Module not found.
> ```

What stood out to me in that was the fact there is a .sh executible. It means that they compiled a Linux version without even knowing it. I opened up the game folder and manually ran the .sh file and it opened a native Linux version. If you can force Steam to do that automatically it would allow people to run the game without any tinkering or even having to use Proton. Just an idea.
