### ISSUE TITLE
Unity of Command II (809230)

### ISSUE THREAD

**Issue by Stew-rt** [ValveSoftware/Proton#3841]
# Compatibility Report
- Name of the game with compatibility issues: Unity of Command II
- Steam AppID of the game: 809230

## System Information
- GPU: Radeon RX Vega 56
- Driver: X.Org Radeon RX Vega (VEGA10, DRM 3.35.0, 5.4.0-29-generic, LLVM 9.0.1)
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 20.0.4
- Kernel version: 5.4.0-29-generic
- Link to full system information report as [Gist](https://gist.githubusercontent.com/Stew-rt/68acc1e19b6849c713bf94316481e6e4/raw/f76cc64eabb3cd94c2bef83ae840cf1f0f3df9eb/stewart-ThinkPad-T480-systemreport.txt):
- Proton version: 5.0-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-809230.log](https://github.com/ValveSoftware/Proton/files/4595120/steam-809230.log)

## Symptoms 
Starting game immediately exits in failure within a few seconds, game window does not even get to open, steam client realises and stops showing the game as "Running"

Interestingly (an admittedly older version of) this game ran fine on my Arch Linux build, I can't remember, but may have been running the game without the runtime... But I have migrated to Ubuntu as the 20.04 release stability was appealing...

## Reproduction
Installed game, start game

**Comment by kisak-valve** [comment]
Possible lines of interest from the log:
```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [WinError 6] Invalid handle

Current thread 0x000000bc (most recent call first):
<no Python frame>
```

**Comment by Stew-rt** [comment]
As a possible note of interest, another game 1292020 (Armoured Commander II) was exiting with the same exception, until the change made by devs at Version 4.0.5.
Their changes are described as:
"
Very minor update to fix the mouseover info on the Campaign Day view while in fullscreen mode.

Edit: Also changed the Pyinstaller settings to enable the console - this will create a black console window behind the game window, but it appears to have been causing issues for some players without it, and it should not detract in any way from the game.
"

I wonder if there's an issue with Pyinstaller exes not being able to get back to a shell unless the app is started from a shell?

**Comment by Stew-rt** [comment]
This issue seems to be resolved by Proton 5.0-8

**Comment by kisak-valve** [comment]
Unity of Command 2 crashes often using Proton experimental and after upgrading to Kubuntu 22.04

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5813.
@mokmeister posted on 2022-05-02T12:48:00:

Unity of Command 2 was running well using Proton Experimental under Kubuntu 21.10. However, since upgrading to Kubuntu 22.04 the games crashes regularly. The latest crash produced these results in log.txt:

INF 2022-05-02 13:29:38,437                tools.steam_api:230  Shutting down Steam
ERR 2022-05-02 13:29:38,442                       uoc2-exe:24   Traceback (most recent call last):
ERR 2022-05-02 13:29:38,442                       uoc2-exe:24     File "uoc2-exe.py", line 17, in <module>
ERR 2022-05-02 13:29:38,443                       uoc2-exe:24     File "E:\code\\uoc2\\uoc2\\main.py", line 311, in main
ERR 2022-05-02 13:29:38,444                       uoc2-exe:24     File "E:\code\\uoc2\\engine\\ui\\system.py", line 716, in main_loop
ERR 2022-05-02 13:29:38,444                       uoc2-exe:24   OSError: exception: access violation writing 0x0000000000000054

based on the crash log, developer reports that the game crashes in SDL_GL_SwapWindow()

**Comment by kisak-valve** [comment]
Hello @mokmeister, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by mokmeister** [comment]
https://gist.github.com/mokmeister/41f74e0db90b171223ecf2be9c1243c4

**Comment by Randaly** [comment]
This has regressed in between 7.0-6 and 8.0-2.

Repro steps:
* Start a campaign (this also fails on saves created under 7.0-6, to be clear, but doesn't fail on an identical setup with 7.0-6)
* In the campaign, enter a scenario
* It fails to launch, there is a small popup window with the title "cx_Freeze: Pyth... in main script" giving no error message, directing you to look at a log file in %localappdata%/.uoc2/log.txt. This contains the following log:
INF 2023-06-04 15:31:34,240                tools.steam_api:267  Shutting down Steam
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24   Traceback (most recent call last):
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "uoc2-exe.py", line 17, in <module>
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\uoc2\main.py", line 311, in main
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\system.py", line 690, in main_loop
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\system.py", line 1046, in _run_coroutines_and_signals
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\tools\coroutine.py", line 107, in cr_switch
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\tools\coroutine.py", line 137, in switch
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\uoc2\main_screen\ctrl.py", line 1839, in _cr_setup_world
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 110, in _switch_state
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 121, in _switcher_gen
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 186, in dispatch_internal_event
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Env\Py311\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
ERR 2023-06-04 15:31:34,244                       uoc2-exe:24     File "C:\Code\uoc2\uoc2\main_screen\ctrl.py", line 384, in on_leave__campaign
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\ctrl.py", line 30, in deactivate
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 110, in _switch_state
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 121, in _switcher_gen
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\engine\ui\state.py", line 186, in dispatch_internal_event
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Env\Py311\Lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\uoc2\main_screen\campaign_ctrl.py", line 158, in on_leave__active
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\uoc2\state\campaign\campaign.py", line 252, in save
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Code\uoc2\tools\file_utils.py", line 88, in copy_tree
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24     File "C:\Programs\Python311\Lib\shutil.py", line 559, in copytree
ERR 2023-06-04 15:31:34,245                       uoc2-exe:24   OSError: [WinError 123] Invalid name: 'C:\\users\\steamuser\\AppData\\Local\\.uoc2\\save\\campaigns\\don.usg'

Here's the PROTON_LOG:

[steam-809230.log](https://github.com/ValveSoftware/Proton/files/11647411/steam-809230.log)

**Comment by kisak-valve** [comment]
Hello @Randaly, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you're using the Steam client beta, then please include `Steam Runtime Diagnostics` instead.

**Comment by Randaly** [comment]
https://gist.github.com/Randaly/fd726d656d3954d52d67c6eeb01bc335

**Comment by sith-on-mars** [comment]
I can confirm that starting a campaign still crashes as of Proton 9. Proton 7 works fine with campaigns with `PYOPENGL_PLATFORM=nt %command%` in Steam launch parametre.
