### ISSUE TITLE
Campfire Pro (965480)

### ISSUE THREAD

**Issue by MollyMaclachlan** [ValveSoftware/Proton#3860]
# Compatibility Report
- Name of the game with compatibility issues: Campfire Pro
- Steam AppID of the game: 965480

## System Information
- GPU: GTX 1050 Ti
- Driver/LLVM version: NVIDIA 440.44
- Kernel version: 4.4.186
- Proton version: 5.0-7

[Full system information](https://gist.github.com/MurdoMaclachlan/06f3a4c00c98d7306594e50cf9fc5874)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Log](https://gist.github.com/MurdoMaclachlan/f0e3187ba07d5f1d9d4003bca41a734f)

## Symptoms
I experience two strange issues with this program.

The first issue won't be found in the log, because by its nature it can't be logged. Campfire Pro only successfully runs for me if I include the PROTON_LOG=1 command in the launch options. If I remove the command, it will launch and then immediately crash before a window even pops up.

The second issue didn't occur for me when I ran the demo version with normal wine, but as soon as I used the Steam version with Proton, it started. Whenever I attempt to put a diacritic over a letter, it will instead print the diacritic and letter next to each other; e.g. I try to write ö and I get ¨o. It seems to be automatically printing the diacritic without waiting for a letter input, and even when I press the letter at the exact same time as the keys for the diacritic, it's still separating the diacritic from the letter.

## Reproduction
For the first issue: attempt to run the game without the PROTON_LOG=1, then attempt to run the game without it.

For the second issue, attempt to write any diacritic over any letter.

**Comment by kisak-valve** [comment]
Possible line of interest from the log: `fixme:dwrite:dwritefontface5_HasVariations 0x5c0220: stub`

**Comment by MollyMaclachlan** [comment]
So, I ran Steam in a terminal to try and get a log for the crash it does without a command. I found the part of the log that came up the exact moment Campfire crashed.

```
net.js:282
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:282:24)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5486:13)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:302:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
Game removed: AppID 965480 "", ProcID 15889
```

A link to the full terminal output in a gist is [here](https://gist.github.com/MurdoMaclachlan/472d6274db17d9233987fbb5700ead72).

**Comment by MollyMaclachlan** [comment]
I hadn't used Campfire Pro in ages, but thought I'd come back to it recently. Unfortunately now it runs but creates no window, so I can't do anything with it. After a few seconds of this, it will start to spit out massive repeated output to the log; after only a few seconds of this it was a 30MB log with over 300,000 lines. I put the first 4,000 lines in a [gist here](https://gist.github.com/MurdoMaclachlan/2cee266ad5f49d02bfb814ca0e895a78).

Running it with Proton 6.6-5 primarily, but tried a few other versions and they gave the same result.
