### ISSUE TITLE
Cannot untar the directory like "c:" and "z:" 

### ISSUE THREAD

**Issue by engineer1109** [ValveSoftware/Proton#4173]
# Compatibility Report
- Name of the game with compatibility issues:
- All the games on windows

## System Information
- GPU: RTX2070
- Driver/LLVM version: NVIDIA 450.57
- Kernel version: 5.4.0-45
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0.9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Logs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tarfile.py", line 2229, in makelink
    os.symlink(tarinfo.linkname, targetpath)
OSError: [Errno 22] Invalid argument: '/' -> '/media/wjl/0D6D10D70D6D10D7/steamgames/steamapps/common/Proton 5.0/dist/./share/default_pfx/dosdevices/z:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/wjl/0D6D10D70D6D10D7/steamgames/steamapps/common/Proton 5.0/proton", line 686, in <module>
    g_proton.extract_tarball()
  File "/media/wjl/0D6D10D70D6D10D7/steamgames/steamapps/common/Proton 5.0/proton", line 129, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.8/tarfile.py", line 2026, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.8/tarfile.py", line 2067, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.8/tarfile.py", line 2147, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.8/tarfile.py", line 2239, in makelink
    self._extract_member(self._find_link_target(tarinfo),
  File "/usr/lib/python3.8/tarfile.py", line 2141, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.8/tarfile.py", line 2170, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/wjl/0D6D10D70D6D10D7/steamgames/steamapps/common/Proton 5.0/dist/./share/default_pfx/dosdevices/z:'

```

My System is Ubuntu 20.04
And use python 3.8.2
I cannot untar or mkdir the directory including ":" .
So the "c:" and "z:" cannot be created.

**Comment by kisak-valve** [comment]
Hello @engineer1109, what filesystem are you using with `/media/wjl/0D6D10D70D6D10D7/` and what mount options are you using?

I suspect you're using a secondary Steam Library on an NTFS partition. There's known quirks when using Proton (or wine) on this filesystem and the notes at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows might help.

**Comment by engineer1109** [comment]
@kisak-valve  Thanks. This problem has been solved.
