### ISSUE TITLE
SWORD ART ONLINE Alicization Lycoris (1009290)

### ISSUE THREAD

**Issue by trenton4k** [ValveSoftware/Proton#4200]
# Compatibility Report
- Name of the game with compatibility issues: SWORD ART ONLINE Alicization Lycoris
- Steam AppID of the game:  1009290

## System Information
- GPU: 1070 ti
- Driver/LLVM version: nvidia 450
- Kernel version: 5.8
- https://gist.github.com/trenton4k/218847391f4068d8e11e81d863fed305
- Proton version: proton-5.0-10-rc4 & 5.0.8

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

https://filebin.net/ph5yw01l4tdc85go/steam-1009290.log?t=0105obzn (54mb)

## Symptoms 

launch and crash to desktop

**Comment by qsniyg** [comment]
It appears to segfault repeatedly, but I can't find any relevant information explaining why from the log.

<details>
<summary>Relevant portion of the log</summary>

```
15353.196:00b8:00bc:trace:seh:raise_exception code=406d1388 flags=0 addr=0x7b00fc3e ip=7b00fc3e tid=00bc
15353.196:00b8:00bc:trace:seh:raise_exception  info[0]=0000000100001000
15353.196:00b8:00bc:trace:seh:raise_exception  info[1]=000000001e6a4708
15353.196:00b8:00bc:trace:seh:raise_exception  info[2]=00000000000002f4
15353.196:00b8:00bc:trace:seh:raise_exception  info[3]=000000014113f970
15353.196:00b8:00bc:trace:seh:raise_exception  info[4]=000000001e6a46d0
15353.196:00b8:00bc:trace:seh:raise_exception  info[5]=0000000000010000
15353.196:00b8:00bc:trace:seh:raise_exception  rax=000000000021f450 rbx=000000001e6a46e8 rcx=000000000021f430 rdx=0000000000000000
15353.196:00b8:00bc:trace:seh:raise_exception  rsi=000000000021f560 rdi=000000000021f480 rbp=0000000000000002 rsp=000000000021f410
15353.196:00b8:00bc:trace:seh:raise_exception   r8=0000000000000006  r9=000000000021f530 r10=0000000000000008 r11=0000000000000246
15353.196:00b8:00bc:trace:seh:raise_exception  r12=0000000000000020 r13=0000000000000000 r14=000000014113f970 r15=0000000000000038
15353.196:00b8:00bc:trace:seh:call_vectored_handlers calling handler at 0x69060920 code=406d1388 flags=0
15353.196:00b8:00bc:trace:seh:call_vectored_handlers handler at 0x69060920 returned ffffffff
15353.217:00b8:00bc:trace:seh:raise_exception code=c0000005 flags=0 addr=0x14113cfa1 ip=14113cfa1 tid=00bc
15353.217:00b8:00bc:trace:seh:raise_exception  info[0]=0000000000000000
15353.217:00b8:00bc:trace:seh:raise_exception  info[1]=ffffffffffffffff
15353.217:00b8:00bc:trace:seh:raise_exception  rax=5555555555555555 rbx=000000001f182a90 rcx=0000000000000001 rdx=5555555555555555
15353.217:00b8:00bc:trace:seh:raise_exception  rsi=0000000000000000 rdi=0000000000000006 rbp=000000000021f840 rsp=000000000021f7f0
15353.217:00b8:00bc:trace:seh:raise_exception   r8=000000003365ace0  r9=000000003285ace0 r10=000000003365ace0 r11=0000000000000080
15353.217:00b8:00bc:trace:seh:raise_exception  r12=0000000141f96350 r13=0000000000000438 r14=0001000000000231 r15=0000000000000000
```

</details>

**Comment by iMonZ** [comment]
Any news?

**Comment by magiruuvelvet** [comment]
I once found a workaround to the crash. Setting the launch options to `LANG=C %command%` makes the game work. It can't handle locales correctly as it seems.

See my ProtonDB report here (same username as GitHub): https://www.protondb.com/app/1009290

**Comment by iMonZ** [comment]
> I once found a workaround to the crash. Setting the launch options to `LANG=C %command%` makes the game work. It can't handle locales correctly as it seems.
> 
> See my ProtonDB report here (same username as GitHub): https://www.protondb.com/app/1009290

Works perfectly fine!
Game is playable

**Comment by Nagakuro** [comment]
So this game seems to work practically flawlessly, HOWEVER there is a massive issue with the games story CG's past the initial main story. When they started doing side stories with free updates, and their first Paid DLC, they started using Live2D for their sprites/CG scenes after games main scenario.

https://youtu.be/vAwthaURaBs

I go into this issue for around the first 4 minutes of this video I made showcasing the game on Steam Deck, aside from this issue the game works practically flawlessly.

Just felt like reporting this issue so you guys can potentially look into it and see if there is a possible fix, as can't fix something if it ain't reported. I've used the game on every version of Proton from Proton GE 7-10 up to 7-24 GE, as well as Proton 6.3-8 and 7.0-3 and Proton Experimental Bleeding Edge.

**Comment by kisak-valve** [comment]
Hello @Nagakuro, with a mainline Proton version, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the render issue, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by Nagakuro** [comment]
# Compatibility Report
- Name of the game with compatibility issues: SWORD ART ONLINE Alicization Lycoris
- Steam AppID of the game: 1009290

## System Information
- GPU: AMD Custom APU 0405/Steam Deck
- Driver/LLVM version: Mesa 22.0.2
- Kernel version: 5.13.0-valve20-1-neptune-02207-gbd986a7e1c7f
- Proton version: 7.0-3 mainline

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1009290.log](https://github.com/ValveSoftware/Proton/files/9035296/steam-1009290.log)

## Symptoms

Game uses Live2D Cinematics for some cutscenes/Visual Novel scenes for post launch content, and the sprites/CGs for the Visual Novel portions don't show up sometimes.

What it looks like on Steam Deck
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/107516271/177052456-0f6c44ec-303b-41c9-9a22-bfd0455865d8.jpg)
What it looks like on Normal Desktop
<img width="1280" alt="SWORD ART ONLINE Alicization Lycoris Screenshot 2022 07 03 - 13 18 55 41" src="https://user-images.githubusercontent.com/107516271/177052477-dc9c5ef3-f4c4-4321-9ab0-a9e66d9f6171.png">


## Reproduction

Visit the Gallery with a save file that has the story mode completed and the entire gallery unlocked, and view/watch past scenes from the DLC/Updates.

You can reproduce this game just by playing and beating the main games 50+ hour story and starting the DLC/Free Update Stories since it only happens in DLC/Free Update Stories.

**Comment by Nagakuro** [comment]
> Hello @Nagakuro, with a mainline Proton version, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the render issue, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

there we go, just made a proper report.

**Comment by kisak-valve** [comment]
Thanks, can you check if setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` has an effect?

**Comment by Nagakuro** [comment]
> Thanks, can you check if setting the game's launch options to `PROTON_USE_WINED3D=1 %command%` has an effect?

the game now immediately crashes upon Launch with this command with Proton 7.0-3.

Want me to run `PROTON_USE_WINED3D=1 %command%` and `PROTON_LOG=1 %command%` as well to generate a log for the crash?

**Comment by kisak-valve** [comment]
I was hoping we'd get lucky and get a hint that scoped the render quirk to DXVK or RADV. The launch option isn't considered supported, but it is sometimes useful for troubleshooting. The crash isn't particularly interesting.

**Comment by Nagakuro** [comment]
Ah, well just thought I'd report it, so you guys can mark down the bug, and work on it eventually, rather than me not reporting it, and just pray it eventually magically starts working one day.

Hopefully it's fixable, cause outside of this issue, I think the game could be marked as playable with exceptions, such as launching the game with EAC disabled (which is a prompt when you boot up the game, that the devs added), as the games default configuration runs well enough, and shows steam deck icons, text is readable and such.

**Comment by zaps166** [comment]
I've got problem with screen tearing on Proton 6.3-8 and 7.0-6 and Experimental. The latest Proton which works correctly is 5.13-6. Very similar to https://github.com/ValveSoftware/Proton/issues/827#issuecomment-1421337277 but this game requires Proton 5.13-6 instead of Proton 6.3-8 to run smoothly.

**Comment by kisak-valve** [comment]
Hello @zaps166, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by zaps166** [comment]
Hey @kisak-valve 

[logs.zip](https://github.com/ValveSoftware/Proton/files/10797278/logs.zip)
https://gist.github.com/zaps166/a06fad61789862f52028e2f1b522cb83

I found `2582.846:0108:010c:fixme:vulkan:wine_vk_surface_set_offscreen Redirecting vulkan surface offscreen, expect degraded performance.` in logs, maybe that's a problem. I can't find it in Proton 5.13-6 logs which runs correctly.

**Comment by alasky17** [comment]
@zaps166 Could you test if adding WINE_DISABLE_VK_CHILD_WINDOW_RENDERING_HACK=1 %command% to the launch options for this game fixes the screen tearing (with Proton Experimental)?  I had forgotten when I responded to the other comment, but you should be able to test that for any game :)

**Comment by zaps166** [comment]
@alasky17 It works! I didn't know about this envvar :sweat_smile:

**Comment by alasky17** [comment]
@zaps166 It is a new one :) Created specifically for the Tales of Berseria issue, but now we can force it on for other impacted games.

**Comment by zaps166** [comment]
> @zaps166 It is a new one :) Created specifically for the Tales of Berseria issue, but now we can force it on for other impacted games.

Ok, it's working here, too :)

Btw. why it has to be disabled for other games?

**Comment by alasky17** [comment]
@zaps166 The change isn't "correct" and it is in a highly sensitive area of the code, so there is a very good chance that it would break some other games that didn't need the hack in the first place.  This is much safer until the distant future when this can be implemented correctly :)

**Comment by zaps166** [comment]
Ok, thanks!

**Comment by Kirit29** [comment]
@alasky17 any luck tracking down the issue with missing character rendering in post-game dialog screens?

**Comment by Nagakuro** [comment]
> @alasky17 any luck tracking down the issue with missing character rendering in post-game dialog screens?

I thought that was already fixed with Proton 8, and Proton GE 7.55 and up? Is there still random ones that are missing?

**Comment by tamodolo** [comment]
The game isn't starting here.

This is all the log outputs using [PROTON_LOG=1 %command%](https://github.com/ValveSoftware/Proton#runtime-config-options) 

Proton: 1684512816 proton-8.0-2d
SteamGameId: 1009290
Command: ['/media/id/SSD 1tb/SteamLibrary/steamapps/common/SWORD ART ONLINE Alicization Lycoris/sao_al.exe']
Options: {'forcelgadd'}
depot: 0.20230509.49493
pressure-vessel: 0.20230509.0 scout
scripts: 0.20230509.0
sniper: 0.20230509.49493 sniper 0.20230509.49493
Kernel: Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None

any idea?

**Comment by kisak-valve** [comment]
Hello @tamodolo, a header only log hints that something went wrong before the game itself had a chance to run. If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew when you tell Steam to run the game?

Also, what filesystem are you using with `/media/id/SSD 1tb/SteamLibrary/`?

**Comment by tamodolo** [comment]
> Hello @tamodolo, a header only log hints that something went wrong before the game itself had a chance to run. If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew when you tell Steam to run the game?
> 
> Also, what filesystem are you using with `/media/id/SSD 1tb/SteamLibrary/`?

Helo @kisak-valve ! Thanks for the orientation. The filesystem is NTFS. Next is the Steam output when running on terminal (after reading I'm not sure what is wrong actualy...):

GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp continues with user response "1"
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale pt_BR.UTF-8...
pressure-vessel-locale-gen: Generated locale pt_BR.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[4466]: W: Container startup will be faster if missing locales are created at OS level
Proton: Upgrading prefix from None to 8.0-101 (/media/id/SSD 1tb/SteamLibrary/steamapps/compatdata/1009290/)
Traceback (most recent call last):
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1636, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1431, in init_session
    g_compatdata.setup_prefix()
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 789, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/id/SSD 1tb/SteamLibrary/steamapps/compatdata/1009290/pfx//dosdevices/c:'
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1009290, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0LANG=C PROTON_LOG=1 /home/id/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1009290 -- /home/id/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/id/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0'/proton waitforexitandrun  '/media/id/SSD 1tb/SteamLibrary/steamapps/common/SWORD ART ONLINE Alicization Lycoris/sao_al.exe'\0
Game process added : AppID 1009290 "LANG=C PROTON_LOG=1 /home/id/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1009290 -- /home/id/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/id/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0'/proton waitforexitandrun  '/media/id/SSD 1tb/SteamLibrary/steamapps/common/SWORD ART ONLINE Alicization Lycoris/sao_al.exe'", ProcID 4515, IP 0.0.0.0:0
chdir "/media/id/SSD 1tb/SteamLibrary/steamapps/common/SWORD ART ONLINE Alicization Lycoris"
ERROR: ld.so: object '/home/id/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/id/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/id/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/id/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/id/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""

(steam:3330): GLib-GObject-CRITICAL **: 15:15:57.912: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:3330): GLib-GObject-CRITICAL **: 15:15:57.912: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
GameAction [AppID 1009290, ActionID 2] : LaunchApp changed task to Completed with ""
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[4606]: W: Container startup will be faster if missing locales are created at OS level
Proton: Upgrading prefix from None to 8.0-101 (/media/id/SSD 1tb/SteamLibrary/steamapps/compatdata/1009290/)
Traceback (most recent call last):
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1636, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1431, in init_session
    g_compatdata.setup_prefix()
  File "/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0/proton", line 789, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/id/SSD 1tb/SteamLibrary/steamapps/compatdata/1009290/pfx//dosdevices/c:'
Game process removed: AppID 1009290 "LANG=C PROTON_LOG=1 /home/id/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1009290 -- /home/id/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/id/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/media/id/SSD 1tb/SteamLibrary/steamapps/common/Proton 8.0'/proton waitforexitandrun  '/media/id/SSD 1tb/SteamLibrary/steamapps/common/SWORD ART ONLINE Alicization Lycoris/sao_al.exe'", ProcID 4515 
ThreadGetProcessExitCode: no such process 4649
ThreadGetProcessExitCode: no such process 4518
ThreadGetProcessExitCode: no such process 4517
ThreadGetProcessExitCode: no such process 4516
Uploaded AppInterfaceStats to Steam

(steam:3330): GLib-GObject-CRITICAL **: 15:15:59.394: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:3330): GLib-GObject-CRITICAL **: 15:15:59.394: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:3330): GLib-GObject-CRITICAL **: 15:16:01.340: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:3330): GLib-GObject-CRITICAL **: 15:16:01.340: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by kisak-valve** [comment]
`OSError: [Errno 22] Invalid argument: '../drive_c' -> '/media/id/SSD 1tb/SteamLibrary/steamapps/compatdata/1009290/pfx//dosdevices/c:'` is the key detail in the terminal spew and that is being tracked at #5168.

Proton interacting with NTFS is known to be finicky, and the general recommendation is to use a Linux native filesystem instead.

**Comment by tamodolo** [comment]
Thanks @kisak-valve ! indeed changing the ssd to ext4 made the game actually start and show something on screen. just to crash again. This is the log:

[steam-1009290.log](https://github.com/ValveSoftware/Proton/files/11715700/steam-1009290.log)

**Comment by Artoria2e5** [comment]
@kisak-valve 
> Proton interacting with NTFS is known to be finicky, and the general recommendation is to use a Linux native filesystem instead.

I'd really rather see people stop saying this line and start blaming the udisks default instead. Before they changed the mount options everything worked fine.

**Comment by Kirit29** [comment]
> > @alasky17 any luck tracking down the issue with missing character rendering in post-game dialog screens?
> 
> I thought that was already fixed with Proton 8, and Proton GE 7.55 and up? Is there still random ones that are missing?

All of them are still missing as of proton 8 and ge 7.55 and up. At least on my steam deck they are. It doesn't seem to be fixed yet.
Also sorry for the extremely late reply

**Comment by Nagakuro** [comment]
> > > @alasky17 any luck tracking down the issue with missing character rendering in post-game dialog screens?
> > 
> > 
> > I thought that was already fixed with Proton 8, and Proton GE 7.55 and up? Is there still random ones that are missing?
> 
> All of them are still missing as of proton 8 and ge 7.55 and up. At least on my steam deck they are. It doesn't seem to be fixed yet. Also sorry for the extremely late reply

I hate to be the bearer of bad news but it is working just fine for me on the steam deck with proton 8.0-3
Just booted up the game with Proton 8.0-3, Proton Experimental, and Proton GE.8-13

For reference I am curious, do you update your drivers often in Desktop mode via the Discover app updates section, as well as the latest update inside of game mode UI from system settings? Cause if your MESA Drivers are out of date that could explain it.

Edit: Also just had two friends who also have steam deck and this game check and they don't have issues either.

here is some photos of some post-game dialog screens, from dlc's and such.

![1](https://github.com/ValveSoftware/Proton/assets/107516271/d9f27458-b950-4a99-a6f4-a330f5f40b26)
![2](https://github.com/ValveSoftware/Proton/assets/107516271/e6b9a22f-1b10-4b8c-b9da-e2c7da3389a3)
