### ISSUE TITLE
Error upgrading old prefix (Game: Planetbase – 403190)

### ISSUE THREAD

**Issue by Eddi-z** [ValveSoftware/Proton#5118]
This game ran fine a few years ago, now it doesn't start

```
Proton: Upgrading prefix from 3.16-1 to 6.3-3 (/home/johannes/Steam/steamapps/compatdata/403190/)
Proton: Removing old xinput registry entries.
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 1264, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 1078, in init_session
    g_compatdata.setup_prefix()
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 649, in setup_prefix
    self.migrate_user_paths()
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 623, in migrate_user_paths
    merge_user_dir(src=old, dst=new)
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 102, in merge_user_dir
    try_copy(src_file, dst_file, copy_metadata=True)
  File "/home/johannes/Steam/steamapps/common/Proton 6.3/proton", line 123, in try_copy
    shutil.copy2(src, dst)
  File "/usr/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/home/johannes/Steam/steamapps/compatdata/403190/pfx/drive_c/users/steamuser/My Documents/Planetbase'
```

**Comment by aeikum** [comment]
Hi @Eddi-z, thanks for reporting. See also #5102 . I think this issue is fixed on on current Proton Experimental, or on the "issue5102" branch of the Proton 6.3 app.

**Comment by Eddi-z** [comment]
thanks, i'll test it soon. that other ticket had a misleading title so i was unable to find that it's the same bug

**Comment by Eddi-z** [comment]
well, close, but no cigar.

error message changed to

```
Proton: Upgrading prefix from 4.11-2 to 6.3-3 (/home/johannes/Steam/steamapps/compatdata/403190/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/johannes/Steam/steamapps/common/Proton - Experimental/proton", line 1276, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/johannes/Steam/steamapps/common/Proton - Experimental/proton", line 1090, in init_session
    g_compatdata.setup_prefix()
  File "/home/johannes/Steam/steamapps/common/Proton - Experimental/proton", line 726, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/johannes/Steam/steamapps/common/Proton - Experimental/proton", line 546, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/johannes/Steam/steamapps/compatdata/403190/tracked_files'
```
