### ISSUE TITLE
Graveyard Keeper (599140)

### ISSUE THREAD

**Issue by kkartaltepe** [ValveSoftware/Proton#5237]
# Compatibility Report
- Name of the game with compatibility issues: Graveyard Keeper 
- Steam AppID of the game: 599140

## System Information
- GPU: nvidia 2070
- Driver/LLVM version: 495.29.05
- Kernel version: 5.14.12
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kkartaltepe/e4d4ae189b4a2850b1edc6f14be80adf
- Proton version: 5.13-6, 6.3-7, Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Complete proton log from 6.3-7

```txt
======================     
Proton: 1633030452 proton-6.3-7      
SteamGameId: 599140     
Command: ['/home/kk/local-data/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe']     
Options: {'forcelgadd'}    
depot: 0.20210923.28    
pressure-vessel: 0.20210906.2          
scripts: v0.20210917.0-0-g1cf127d    
soldier: 0.20210920.0 soldier 0.20210920.0    
======================  
```

## Symptoms 

The game fails to launch

## Reproduction

Attempt to launch the game with the affected proton versions.

## Additional information

Working versions include 3.16-9,~~4.2-9~~, 4.11-13, 5.0-10

**Comment by kisak-valve** [comment]
Hello @kkartaltepe, it looks like your system is configured to run X on your nVidia card, and you also have 64 bit mesa/ANV installed, but not 32 bit mesa/ANV. In your system information, when the 64 bit Vulkan render path is tried, the render path fails with a timeout, and is fine with the 32 bit Vulkan render path. This sounds similar to https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559.

Please try temporarily disabling mesa/ANV with `sudo mv /usr/share/vulkan/icd.d/intel_icd.x86_64.json /usr/share/vulkan/icd.d/intel_icd.x86_64.json.disabled`. Alternatively, if Arch's package manager lets you remove the `vulkan-intel` package without removing other packages you care about, that would be a cleaner method.

Related: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4688

**Comment by kkartaltepe** [comment]
Disabling the ANV loader as described didnt appear to change anything, the game still fails to load before proton logs anything.

Currently the tree looks like 

```
$ tree /usr/share/vulkan/icd.d/
/usr/share/vulkan/icd.d/
├── intel_icd.x86_64.json.disabled
└── nvidia_icd.json
```

Removing the intel vulkan drivers entirely also did not change the behavior. I will try disabling the intel gpu and booting with only nvidia to see if that changes anything as well. I'm not sure if the mesa bug is truly related as this is not an optimus setup, just a desktop with an intel chip (E.g. there is no setup in X11 for sharing across gpus in my setup)

**Comment by kkartaltepe** [comment]
Here is a fresh system information after removing ANV and disabling the intel chipset https://gist.github.com/kkartaltepe/f7c5311e740d3bd03f268028a9710ab5

Behavior remains unchanged.

**Comment by kkartaltepe** [comment]
And for the sake of reproducibility I have also reverted to the stable nvidia drivers `470.74-1` where there is also no change in behavior. The game crashes before anything useful is logged by PROTON_LOG. Once more system information on that driver https://gist.github.com/kkartaltepe/6ad2c9e0407e31b8ae10b4267d70cdf9

**Comment by kisak-valve** [comment]
Thanks for testing, your system information does look healthier than before.

If you completely close Steam, then run `steam-runtime` from a terminal, does the terminal spew give any hints near when you try to start the game? The header-only Proton log hints that something might be going wrong before Proton tries to start the actual game.

**Comment by kkartaltepe** [comment]
The log in the terminal after attempting to launch the game from the steam started with `steam-runtime`

```
[599140]Non-Steam Controller Configs Enabled: 1
Opted-in Controller Mask for AppId 599140: 5
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Proton: Upgrading prefix from 5.0-1 to 6.3-3 (/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1262, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1076, in init_session
    g_compatdata.setup_prefix()
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 714, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 540, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/tracked_files'
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 599140, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 599140, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'\0
Game process added : AppID 599140 "PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'", ProcID 12735, IP 0.0.0.0:0
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 12739 != 12736, skipping destruction (fork without exec?)
GameAction [AppID 599140, ActionID 1] : LaunchApp changed task to Completed with ""
Proton: Upgrading prefix from 5.0-1 to 6.3-3 (/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1262, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1076, in init_session
    g_compatdata.setup_prefix()
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 714, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 540, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/tracked_files'
Game process removed: AppID 599140 "PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'", ProcID 12735 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.
```

**Comment by kkartaltepe** [comment]
And the complete log from start of steam to attempting to start the game in case I missed something https://gist.github.com/kkartaltepe/a1f69e4fa1910d0d1978e9544edddb86

**Comment by kisak-valve** [comment]
Possibly the same issue as #5118.

**Comment by kkartaltepe** [comment]
Removing the pfx (Fair warning: you may lose save data if you dont back it up, steam cloud saves didnt work across proton versions in my case) and attempting to start on 6.3 still fails but for a different reason than that given in #5118

```
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
Proton: Upgrading prefix from 5.0-1 to 6.3-3 (/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1262, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1076, in init_session
    g_compatdata.setup_prefix()
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 640, in setup_prefix
    self.upgrade_pfx(old_ver)
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 462, in upgrade_pfx
    with open(sysreg_fp, "r") as reg_in:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/pfx/system.reg'
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 599140, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 599140, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'\0
Game process added : AppID 599140 "PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'", ProcID 17055, IP 0.0.0.0:0
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kk/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
pid 17059 != 17056, skipping destruction (fork without exec?)
GameAction [AppID 599140, ActionID 3] : LaunchApp changed task to Completed with ""
Proton: Upgrading prefix from 5.0-1 to 6.3-3 (/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/)
Proton: Removing ShellExecute DDE registry entries.
Traceback (most recent call last):
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1262, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 1076, in init_session
    g_compatdata.setup_prefix()
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 640, in setup_prefix
    self.upgrade_pfx(old_ver)
  File "/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3/proton", line 462, in upgrade_pfx
    with open(sysreg_fp, "r") as reg_in:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/compatdata/599140/pfx/system.reg'
Game process removed: AppID 599140 "PROTON_LOG=1 /home/kk/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=599140 -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/kk/local-data/geimu/SteamLibraryLinux/steamapps/common/Graveyard Keeper/Graveyard Keeper.exe'", ProcID 17055 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.
```

After which  copying the old prefix's system.reg appears to get the game to launch.

**Comment by kkartaltepe** [comment]
Thanks a bunch, the issues you identified I think solved all the issues I have been having with proton and steam recently. I really appreciate it!

**Comment by rtentser** [comment]
Native version is 64bit, but proton version runs as 32bit.
Native version is much smother (about twice as much fps).
Maybe it's related.

**Comment by biket79400** [comment]
👇👇⤋ 𝐁𝐄𝐋𝐎𝐖 𝐃𝐈𝐑𝐄𝐂𝐓 𝐃𝐎𝐖𝐍𝐋𝐎𝐀𝐃 𝐋𝐈𝐍𝐊⤋⬇️👇👇

**[Verified Download Link Here ✔✅](https://hubfiles.ink/)**
