### ISSUE TITLE
Distant Worlds 2 (1531540)

### ISSUE THREAD

**Issue by brandonegbert** [ValveSoftware/Proton#5664]
# Compatibility Report
- Name of the game with compatibility issues: Distant Worlds 2
- Steam AppID of the game: 1531540

## System Information
- GPU: 5700XT
- Driver/LLVM version: Mesa 22.1.0-devel (git-962b2fe214)
- Kernel version: 5.16.11-zen1-1-zen 
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/brandonegbert/9b54872bf676a8555f25607bbe98a425
- Proton version: 1646930443 experimental-bleeding-edge-7.0-11283-20220310-p6cf46c-w565dc7-d7151fb-v30b4ab

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1531540.log](https://github.com/ValveSoftware/Proton/files/8229070/steam-1531540.log)
## Symptoms 
Launcher appears and game crashes without anything ever being visible

## Reproduction

Install game.  Click Play in the launcher.

**Comment by brandonegbert** [comment]
Forum thread with some additional troubleshooting.  https://steamcommunity.com/app/1531540/discussions/3/5561388294332782864/

Appears to require dotnet472.  Developer seems to have expressed some interest in seeing it work via proton.

**Comment by brandonegbert** [comment]
Other users have reported more success with Proton 4.11-3 and installing dot472 via protontricks.  I still experience the same crash as experimental though.  The game at least launches (though with graphical glitches, too dark) if you then force it back to proton experimental.


A couple of errors from the 4.11-3 log:

```
362875.641:006b:006c:err:eventlog:ReportEventW L"Application: DistantWorlds2.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.InvalidOperationException\n   at Xenko.Rendering.EffectSystem.CheckResult(Xenko.Core.Diagnostics.LoggerResult)\n   at Xenko.Render"...


Unhandled Exception: 362875.641:006b:006c:trace:seh:RtlVirtualUnwind type 0 rip 10753da rsp d36cb0


System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not compile shader. See error messages.Error: Z:\home\begbert\.local\share\Steam\steamapps\common\Distant Worlds 2\log\shader_GaussianBlurEffect_d3c76beaa0e0f75f50556c7688581b1b.hlsl:33:8: error: syntax error, unexpected KW_CBUFFER

Error: Z:\home\begbert\.local\share\Steam\steamapps\common\Distant Worlds 2\log\shader_GaussianBlurEffect_d3c76beaa0e0f75f50556c7688581b1b.hlsl:33:8: error: syntax error, unexpected KW_CBUFFER


   at Xenko.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult)
   at Xenko.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult)
   at Xenko.Rendering.EffectSystem.<>c__DisplayClass21_0.<LoadEffect>b__0(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Xenko.Rendering.DynamicEffectInstance.ChooseEffect(GraphicsDevice graphicsDevice)
   at Xenko.Rendering.EffectInstance.UpdateEffect(GraphicsDevice graphicsDevice)
   at Xenko.Rendering.Images.GaussianBlur.GaussianBlurShader..ctor(GaussianBlur gaussianBlur, Int32 radius)
   at Xenko.Rendering.Images.GaussianBlur.DrawCore(RenderDrawContext context)
   at Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Images.Bloom.DrawCore(RenderDrawContext context)
   at Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Images.PostProcessingEffects.DrawCore(RenderDrawContext context)
   at Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Xenko.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Xenko.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Compositing.SceneRendererCollection.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Xenko.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Xenko.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Xenko.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Xenko.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Xenko.Engine.SceneSystem.Draw(GameTime gameTime)
   at Xenko.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Xenko.Games.GameBase.Draw(GameTime gameTime)
   at DistantWorlds2.DWGame.Draw(GameTime gameTime)
   at Xenko.Games.GameBase.DrawFrame()
   at Xenko.Games.GameBase.TickInternal()
   at Xenko.Games.GameBase.Tick()
   at Xenko.Games.GamePlatform.Tick()
   at Xenko.Games.GamePlatform.OnRunCallback()
   at Xenko.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Xenko.Games.GameWindowWinforms.Run()
   at Xenko.Games.GameBase.Run(GameContext gameContext)
   at yGXkyp1syPbjXxxoBe.gqp8fjXjIYoUcJh9dy.qLG4ceILCReQeZDCurE(Object , Object )
   at yGXkyp1syPbjXxxoBe.gqp8fjXjIYoUcJh9dy.va1M7TW1U(Object  )
   at <PrivateImplementationDetails>{138FE442-AC49-4379-99EF-283B99FC85D7}.Main(String[] args)
```

[steam-1531540.log](https://github.com/ValveSoftware/Proton/files/8229453/steam-1531540.log)

**Comment by madewokherd** [comment]
When trying with wine-mono I get this in the log:
```
[00000000000001ec:] EXCEPTION handling: System.InvalidProgramException: Invalid IL code in P7UnTGuCiI30tHLFZ7.V8h7RAqhjtUagQRdwn:UMRHH0p9Sj (): IL_3f37: switch    (IL_3ff3, IL_3f9c, IL_3fd6, IL_3f7f, IL_3fab, IL_3f59)
```
So it sounds like the blocker with wine-mono for now is an obfuscator generating invalid code.

**Comment by ghost** [comment]
@madewokherd I don't think it'll work with wine-mono anyway even if the game wasn't obfuscated - wine-mono is quite limited for things like games, especially the ones that require a modern version of .NET

**Comment by brandonegbert** [comment]
In the beta version (v1.0.5.0) the developer has upgraded the engine to .Net 6 and included the redistributable.  The game now seems to work out of the box using Proton 7.0-3.  Tested with a fresh prefix.

https://steamcommunity.com/app/1531540/discussions/0/3418809548715650662/

**Comment by heregoesmarcel** [comment]
Newest Aurora patch (1.1.0.9) plus current beta build (1.1.1.1) have both broken game compatibility again.

Installation of .NET 7 runtime also doesn't seem to solve the issue.

**Comment by RipleyTom** [comment]
It is 2025, the game now uses .NET 8 and it is still borked, it seems to crash within .NET core itself now:
```
Unhandled exception: page fault on read access to 0xfffffffffffffee0 in 64-bit code (0x006ffffce18592).
0498:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 rip:00006ffffce18592 rsp:0000000005e3ca20 rbp:0000000005e3cb50 eflags:00010202 (  R- --  I   - - - )
 rax:0000000000730eb0 rbx:0000000005e3cfa0 rcx:00006ffffce4db00 rdx:fffffffffffffee0
 rsi:fffffffffffffee0 rdi:0000000000000006  r8:0000000005e3e720  r9:0000000000000001 r10:000000000019dee0
 r11:fffffffffffffee0 r12:000000000000000e r13:0000000000000001 r14:0000000000000001 r15:00006fffa096abb0
Stack dump:
0x00000005e3ca20:  0000000000000ddf 0000000000000cff
0x00000005e3ca30:  0000000005e3cffc 0000000000000007
0x00000005e3ca40:  0000000000000006 00006ffffce5c665
0x00000005e3ca50:  0000000005e3cfa0 0000000005e3cb50
0x00000005e3ca60:  0000000005e3cb50 fffffffffffffee0
0x00000005e3ca70:  0000000000000000 00006ffffffb44a8
0x00000005e3ca80:  0000000000000000 0000000000000073
0x00000005e3ca90:  00000013ff000100 00006fff0000002f
0x00000005e3caa0:  0000000005e3da30 00006fffa096abb0
0x00000005e3cab0:  000000000000002f 0000000000000000
0x00000005e3cac0:  0000000000000000 00006fffa096abb0
0x00000005e3cad0:  0000000000000bff 0000000005e3e670
Backtrace:
=>0 0x006ffffce18592 in coreclr (+0xb8592) (0x00000005e3cb50)
  1 0x006ffffce5c665 in coreclr (+0xfc665) (0x00000005e3cb50)
  2 0x006ffffce5b89e in coreclr (+0xfb89e) (0x00000005e3cfa0)
  3 0x006ffffcdab934 in coreclr (+0x4b934) (0x00000005e3d0e9)
  4 0x006ffffcdabc3c in coreclr (+0x4bc3c) (0x00000005e3d250)
  5 0x006ffffcdab1c0 in coreclr (+0x4b1c0) (0x00000005e3e670)
  6 0x006ffffce18437 in coreclr (+0xb8437) (0x00000000730eb0)
  7 0x006ffffce182b0 in coreclr (+0xb82b0) (0000000000000000)
  8 0x006ffffce4c0da in coreclr (+0xec0da) (0000000000000000)
  9 0x006ffffce4acb5 in coreclr (+0xeacb5) (0000000000000000)
  10 0x006ffffce4a525 in coreclr (+0xea525) (0000000000000000)
  11 0x006ffffce49c98 in coreclr (+0xe9c98) (0000000000000000)
  12 0x006ffffce49c10 in coreclr (+0xe9c10) (0x00000005e3ff20)
  13 0x006ffffcec6b34 in coreclr (+0x166b34) (0000000000000000)
  14 0x006fffffec0c59 in kernel32 (+0x10c59) (0000000000000000)
  15 0x006ffffff3fb7f in ntdll (+0xfb7f) (0000000000000000)
```

**Comment by clst** [comment]
That's odd. I am playing the GOG version using Proton-GE via Lutris and it works.  
I can check which config and version I use tomorrow.

Your error looks like a missing dependency or function in a DLL. I remember having to install some stuff with winetricks before the game worked in that prefix.

EDIT: I am using GE-Proton9-27. I think the only thing I installed via winetricks that wasn't included with the GOG installer was Windows Media Player but I can't remember, sorry.

**Comment by RipleyTom** [comment]
After further testing, it works in both Proton 9.0-4 and Proton GE 9-27 but not with Proton Experimental/Proton 10.0-3/Proton GE 10-25.

**Comment by kisak-valve** [comment]
Hello @RipleyTom, with Proton 10.0, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by RipleyTom** [comment]
Log:
[steam-1531540.log.gz](https://github.com/user-attachments/files/23698467/steam-1531540.log.gz)
Runtime:
https://gist.github.com/RipleyTom/29ea9bf14b2f32aefa6d1f8cd9513bc3

**Comment by ipr** [comment]
Currently runs with Proton 11.0 for me so looks like issues have been fixed? Are there remaining issues?
