### ISSUE TITLE
Proton 3.7 build error: KhronosGroup/Vulkan-Docs/v{0}/xml/vk.xml 404 Not Found

### ISSUE THREAD

**Issue by chinanoahli** [ValveSoftware/Proton#5739]
I got this error while I was building proton 3.7:
```
Traceback (most recent call last):
  File "/home/chinanoahli/myProton/src-wine/dlls/winevulkan/make_vulkan", line 3948, in <module>
    main()
  File "/home/chinanoahli/myProton/src-wine/dlls/winevulkan/make_vulkan", line 3915, in main
    download_vk_xml(vk_xml)
  File "/home/chinanoahli/myProton/src-wine/dlls/winevulkan/make_vulkan", line 3894, in download_vk_xml
    urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
make[1]: *** [../proton/Makefile.in:708: /home/chinanoahli/myProton/.wine-post-source] Error 1
make[1]: Leaving directory '/home/chinanoahli/myProton'
make: *** [../proton/Makefile.in:32: nested_make] Error 2
```

The url in this python script was 404:
`https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/v{0}/xml/vk.xml`

**Comment by chinanoahli** [comment]
It looks like this python script `src-wine/dlls/winevulkan/make_vulkan` is generate by makefile.
And this file will be auto delete by make after this error shows.
Is there any way to modify it whith **jsdelivr cdn**, `raw.githubusercontent.com` is not accessible in China.

**Comment by chinanoahli** [comment]
Find it, in file `proton_src_dir/wine/dlls/winevulkan/make_vulkan`, line 3892, replace `https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/v{0}/xml/vk.xml` to `https://cdn.jsdelivr.net/gh/KhronosGroup/Vulkan-Docs@v{0}/xml/vk.xml`.
