### ISSUE TITLE
WARRIORS OROCHI 3 Ultimate Definitive Edition (1879330)

### ISSUE THREAD

**Issue by klaritan** [ValveSoftware/Proton#6006]
# Compatibility Report
- Name of the game with compatibility issues: WARRIORS OROCHI 3 Ultimate Definitive Edition
- Steam AppID of the game: 1879330

## System Information
Steam Deck
Proton version: 7.0-3

## I confirm:
- [ yes ] that I haven't found an existing compatibility report for this game.
- [ yes ] that I have checked whether there are updates for my system available, including beta.

## Symptoms 

- Steam Deck's FPS reports it's running at 57 ~ 58, but the game definitely is running at somewhere around 30fps. Directly comparable with a Windows system set to run at 60fps/30fps for testing sake. Something does not feel right via Proton.
- In-game cutscenes audio and graphics do not match at all. Completely out of sync.
- Occasionally freezes or crashes at pre-rendered scenes (videos).

## Reproduction

Just join in any stage of the story mode.

**Comment by klaritan** [comment]
I found out that the "low FPS feel" and constant stutters only happen on Gaming Mode. It does not happen on desktop mode.
This is most likely due to Wayland (through GameScope) forcing V-Sync and it's having frame pacing issues as the game also has forced V-Sync.

I noticed a handful of games I've also tested after this find have stuttering issues if they have V-Sync enabled in-game.
Wayland's forced V-Sync is already causing a lot of issues including making games like CSGO pretty unplayable at a reasonable level.

**Comment by Bitwolfies** [comment]
Supposedly the next wayland presentation update will have a proper Vsync disable flag, so long as Valve can add this to Gamescope/the play button on Steam once out, this can be resolved.

**Comment by klaritan** [comment]
> Supposedly the next wayland presentation update will have a proper Vsync disable flag, so long as Valve can add this to Gamescope/the play button on Steam once out, this can be resolved.

Sounds like a good news. Where could I read more about this in progress?

**Comment by DebugKirby** [comment]
The game now crashes after the steam deck 3.3 update when trying to load both my interim save and load into story mode
I clicked preparation in the pre battle screen in a mission it crashed and now no longer loads
I've tested both proton experimental and proton ge

**Comment by alasky17** [comment]
> The game now crashes after the steam deck 3.3 update when trying to load both my interim save and load into story mode I clicked preparation in the pre battle screen in a mission it crashed and now no longer loads I've tested both proton experimental and proton ge

@DebugKirby This sounds like the dxvk regression reported here - https://github.com/doitsujin/dxvk/issues/2787  The dev already fixed this and the fix should be included in the next experimental update :)

**Comment by samuraied** [comment]
black/plank screen after logo
the game does not play the cut scene or get to the menu if cutscene is skipped.
i have tried to look for online solutions but nothing worked.

tried turning off async, esync, force dxvk, no dvxk,
tested with proton exp, 7 and 6.

i have steam (flatpak).
fedora 36 on wayland.
CPU AMD ryzen 2700x.
GPU NVIDIA 1080 ti. propriety driver.

i have updated everything to latest.
and i have the following commands at
[https://github.com/ValveSoftware/Proton/blob/proton_5.0/README.md#runtime-config-options](https://steamcommunity.com/linkfilter/?url=https://github.com/ValveSoftware/Proton/blob/proton_5.0/README.md#runtime-config-options)

so far the problem persists, whats more, i notice 2 windows opening up after launching the game, the second window simply says opengl-renderer.

i have also noticed that some windows users are complaining about this as well.
it maybe GPU driver related, NVIDIA specifically. well, this might serve others, beware when buying NVIDIA GPUs, their support is trash, i have read that AMD GPUs are running ok with this game, but sadly cant confirm, be adviced.

**Comment by samuraied** [comment]
the games behavior is as follows,
game starts, koei logo appears, the W appears, frame rate drops from 60 to 2 fps, one minute later, fps goes to 60, plank screen, no audio or video or control, close game with ALT-F4.
attached files are my attempt to fix the game, but nothing changes.

[WO3U_d3d9.log](https://github.com/ValveSoftware/Proton/files/9571912/WO3U_d3d9.log)
[WO3U_d3d11.log](https://github.com/ValveSoftware/Proton/files/9571913/WO3U_d3d11.log)
[WO3U_dxgi.log](https://github.com/ValveSoftware/Proton/files/9571914/WO3U_dxgi.log)

**Comment by JYip93** [comment]
Will this issue that OP mentioned be fixed?

I have the same issue where it Gamescope shows a stable 58fps but it clearly isnt. It's quite apparent the frames are a fair bit lower than shown.

**Comment by samuraied** [comment]
still not fixed, everything updated to latest.

**Comment by alasky17** [comment]
@samuraied Could you get a log of the failure on Proton Experimental?  That is the only build that has any hope of working right now.  You can get a log by putting PROTON_LOG= "+mfplat,+sharedgpures,+vulkan" %command% in the launch options.

**Comment by samuraied** [comment]
hi @alasky17 , i can't do that, i gave up on the game and deleted it. my internet is not fast enough to download it in a timely manner.
i wish you good luck in figuring this out.

just in case you are interested, another game failed in a similar fashion, but with audio still on. its called warhammer 40k retribution. all on experimental with NVIDIA latest drivers on wayland.

**Comment by XanderXAJ** [comment]
I've tested out the game on Steam Deck since it's been marked as Playable in the recent [2023-03 Proton Experimental update](https://github.com/ValveSoftware/Proton/wiki/Changelog). I'm using save data that has been cloud-synced from Windows. I'm using SteamOS Preview along with Proton Experimental as marked by Valve.

**One issue appears to have been fixed**: the 57-58FPS issue is no longer present and the game will _technically_ always report 60FPS.

Outside of that fix, however, **my experience in Game Mode is anything but Playable**. Most of the visual issues others have mentioned still appear to be persistent:
- While Gamescope reports 60FPS only **about half of the frames appear to be delivered to the screen**. Additionally, those delivered frames appear to get **delivered in the wrong order**, i.e. you're rapidly going back and forth in time. (I guess that fits in with the story of the game, but still..!)
    - This applies to everything: videos, menus and gameplay.
- The **picture visibly judders up and down**, almost as if the image is interlaced and getting de-interlaced badly (??)

I haven't seen any crashes in my limited playing, thankfully.

Trying to change settings within the game (changing windowing mode, frame rate limiter) and the OS (removing frame rate cap, allowing tearing) don't appear to help with the issue. Likewise using Developer > Delete Proton files hasn't helped.

**The game works perfectly in Desktop Mode** as reported above, so this might not actually be a Proton issue but a Wayland/Gamescope one [as suggested](https://github.com/ValveSoftware/Proton/issues/6006#issuecomment-1190638623). I don't know how to investigate/report those -- are there any docs or guidance? Much appreciated.

Some good news though: That 57-58FPS issue appears to have been fixed in all other Warriors games I've tried too. However, many of them their own issues. 😄

**Comment by JYip93** [comment]
So I've noticed the latest Proton Experimental runs even worse than it used to. 

As mentioned above by @XanderXAJ, the whole game no matter in game or menu just completely judders and is completely unplayable for me.  And still is not 60fps.

Have to stick to playing this in Desktop Mode. Hoping for a fix soon as it's been a while

**Comment by Kanadeforever** [comment]
Consistent with @XanderXAJ 's description, not only Orochi3 DE, Koei Tecmo's other games also have this problem, it seems that 3D games made with the same engine will have this problem

**Comment by XanderXAJ** [comment]
Trying Proton 8.0, it is actually possible to get correct-looking 60FPS output most of the time... However, I'd argue it's still not Playable for the layman as **the fix needs to be applied every time the game is launched**.

**To _temporarily_ fix the image issues and get 60FPS output:**

1. Override the game's properties to use Proton 8.0
2. After launching the game, go to the Graphics menu and change the window mode (e.g. Fullscreen, Borderless Window or Window) and apply the change.
   - It doesn't matter which you choose, so long as you change it. You may need to do it twice.

In my experience, this window mode change needs to be done every single time the game is launched. That seems a bit too broken for the game to be marked Playable just yet.

This Proton 8.0 behaviour is similar to older versions of Experimental, back when this game was initially marked Playable. Curiously, Experimental seems to have regressed since then, as only 8.0 seems to be able to give proper playable output -- which is unfortunate since the game still uses Experimental by default.

**Comment by samuraied** [comment]
i don't know why, but the game is now worse, it went from crash after a while to crash on start up. 
i have tried multiple fixes and launch commands as well as x11, wayland and gamescope, all failed.

fedora 38, flatpak steam, proton 8.0.1 and experimental.

**Comment by JYip93** [comment]
@XanderXAJ Very interesting. This has actually worked for me too. First time I have been able to get this game running in proper 60fps on Game mode. Despite it being a temp fix for now, it's definitely something I'll stick with until a proper fix is in place.

**Comment by alasky17** [comment]
@samuraied Could you get a log by adding PROTON_LOG=1 %command% of the "crash after a while" and the crash on startup?  Proton 7.0-experimental is still available right now, so you should be able to get logs of both.

**Comment by samuraied** [comment]
@alasky17 here it is, 
i deleted the game a long time go after giving up on it, but i came back since the game was stated to work, sadly it does not.
[steam-1879330_experimental-8.0-20230417.log](https://github.com/ValveSoftware/Proton/files/11312024/steam-1879330_experimental-8.0-20230417.log)
[steam-1879330_proton-6.3-8f.log](https://github.com/ValveSoftware/Proton/files/11312026/steam-1879330_proton-6.3-8f.log)
[steam-1879330_proton-7.0-6e.log](https://github.com/ValveSoftware/Proton/files/11312027/steam-1879330_proton-7.0-6e.log)
[steam-1879330_proton-8.0-1d.log](https://github.com/ValveSoftware/Proton/files/11312028/steam-1879330_proton-8.0-1d.log)

edited to let you know, i have verified the game, and have attempted many launch options, as well as using gamescope, all through flatpak. almost all of my games run as they should, except this one.

**Comment by kisak-valve** [comment]
Hello @samuraied, header only logs hint that something's gone wrong before Proton has a chance to start the actual game. If you completely close Steam, then run `steam` from a terminal, then there's a decent chance you'll see a better hint in the terminal spew when you tell Steam to start the game.

What filesystem are you using with `/mnt/2Booty/SteamLibrary`? I suspect it's formatted NTFS, which Proton is known to be finicky with. If that's the case, then the general recommendation is to use a linux native filesystem instead.

**Comment by samuraied** [comment]
btrfs, not ntfs
i am going to close steam and run it through the terminal, i will post the result shortly

**Comment by samuraied** [comment]
here it is, i fail to see how proton is broken when the same proton runs every other game.
[terminal_output.txt](https://github.com/ValveSoftware/Proton/files/11312237/terminal_output.txt)

edit: i have attempted to run the game in both wayland and x11, same results

**Comment by kisak-valve** [comment]
This is Proton telling us it had a problem with the game's wineprefix.

```
Proton: Upgrading prefix from None to 8.0-100 (/mnt/2Booty/SteamLibrary/steamapps/compatdata/1879330/)
Traceback (most recent call last):
  File "/home/samuraisora/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1642, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/samuraisora/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1437, in init_session
    g_compatdata.setup_prefix()
  File "/home/samuraisora/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 861, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/samuraisora/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 683, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/2Booty/SteamLibrary/steamapps/compatdata/1879330/tracked_files'
```

**Comment by samuraied** [comment]
i have not used wineprefix, how do i reset it ?

ps: thank you for helping

**Comment by samuraied** [comment]
ok, i cant believe it, but the game works, i couldn't figure out how to reset wineprefix, since i did not use it, but then deleted this folder.
steamapps/compatdata/1879330
and it works now, but no cut_scenes. a massive improvement i say. thank you @alasky17 and @kisak-valve for your help.

**Comment by coreyhh2** [comment]
I'm using steam deck, os version 3.7.25. proton 10.0-4

The only thing that doesn't work well in this game are the pre-rendered cutscene videos. Most of them run, but the video is running slow compared to the audio. Its like watching a film in slow motion while the audio plays at regular speed. Some videos don't play at all and instead show a test pattern that can be skipped through. It doesn't crash.

Rest of the game runs great, in engine cutscenes, gameplay, menus. I haven't seen a crash.
