### ISSUE TITLE
Any Proton stable on Manjaro (ModuleNotFoundError: No module named 'filelock'), but experimental work

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/Proton#6105]
# Compatibility Report
- Name of the game with compatibility issues: Any with Proton
- Steam AppID of the game: Any

## System Information
- GPU: RTX 3060 Ti
- Driver/LLVM version: 515.65.01
- Kernel version: 5.19.1-3-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Any stable

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

`PROTON_LOG=1 %command%` is not working because game just not reach it.

## Symptoms 
No game can start with stable Protons, but working with experimental and GE-protons.
This is on Manjaro. With Ubuntu based like Pop!_OS 22.04, no problem.

## Reproduction
Install Manjaro, update and start any game with Proton stable.

The log from steam from terminal is this:

GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Traceback (most recent call last):
  File "/home/death/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 37, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/death/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1245620 -- '/home/death/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/death/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/death/.local/share/Steam/steamapps/common/ELDEN RING/Game/start_protected_game.exe'\0
Game process added : AppID 1245620 "PROTON_LOG=1 /home/death/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1245620 -- '/home/death/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/death/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/death/.local/share/Steam/steamapps/common/ELDEN RING/Game/start_protected_game.exe'", ProcID 9009, IP 0.0.0.0:0
chdir /home/death/.local/share/Steam/steamapps/common/ELDEN RING/Game
ERROR: ld.so: object '/home/death/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/death/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/death/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/death/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/death/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 9013 != 9010, skipping destruction (fork without exec?)
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to Completed with ""
Traceback (most recent call last):
  File "/home/death/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 37, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
Game process removed: AppID 1245620 "PROTON_LOG=1 /home/death/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1245620 -- '/home/death/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/death/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/home/death/.local/share/Steam/steamapps/common/ELDEN RING/Game/start_protected_game.exe'", ProcID 9009 
ThreadGetProcessExitCode: no such process 9121
ThreadGetProcessExitCode: no such process 9011
ThreadGetProcessExitCode: no such process 9010
Uploaded AppInterfaceStats to Steam

**Comment by deathxxx123** [comment]
Hmm i found something and i remember this is not first time, but i don't know what is causing it.
The proton stable is bugged, so i cannot uninstall from steam.
So i delete all proton stable files.
Now it cannot install proton again with error:

GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
GameAction [AppID 1245620, ActionID 1] : LaunchApp failed with AppError_51 with ""
GameAction [AppID 1245620, ActionID 1] : LaunchApp changed task to Failed with ""

But i can uninstall and reinstall proton experimental.
I have this OS for games mainly and i do not modify it.
I remember last time when this is happen i need to remove all steam files + hidden, then reinstall and bug was fixed.
But maybe we can figure out what type of but is this....
Maybe after many proton updates...? I really do not know.

**Comment by deathxxx123** [comment]
When i try start game with Proton stable i got from steam GUI:
`An error occurred while updating ELDEN RING (compatibility tool configuration failed)`

And it does not want to download proton stable anymore

**Comment by deathxxx123** [comment]
What files i can remove to reset steam without losing installed games?

**Comment by deathxxx123** [comment]
I just reset steam and reinstall Proton with success. Otherwise - no way.
