### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '[...]/Local Settings/Application Data' 

### ISSUE THREAD

**Issue by DuckEater54** [ValveSoftware/Proton#6213]
Closest I got to opening was halfway processing vulkan shaders. Ive installed all manner of bullshit, tried using the dxvk=1 command, wined3d11=1 command, [disabling fsync/esync](https://www.reddit.com/r/linux_gaming/comments/lf7txx/sekiro_crashes_on_load_game_protonsteam_play/), installing [these](https://github.com/ValveSoftware/Proton/wiki/Requirements#amdintel) packages, and yet it still doesnt even bother opening.

No log file is created when using LOG=1, except for a single file in ~ called steam-814380.log. And that has nothing useful in it

steam-814380.log
```
======================
Proton: 1660576899 proton-7.0-4
SteamGameId: 814380
Command: ['/media/<USER>/disk/SteamLibrary/steamapps/common/Sekiro/sekiro.exe']
Options: {'forcelgadd'}
depot: 0.20220919.70
pressure-vessel: 0.20220919.0
scripts: v0.20220823.0-0-gcc4e44f
soldier: 0.20220919.0 soldier 0.20220919.0
Kernel: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64
======================
```

I also dont even have a $PROTON_LOG_DIR folder.

system specs are:

```
Hardware model: HP HP laptop 15s-du3xxx
memory: 16 GiB
Processor: 11th gen Intel Core i5-1135G7 @2.40GHz x 8
Graphics: Mesa intel xe graphics (tgl gt2)
disk capacity: 270.5 GB
OS Name: Ubuntu 22.04.1 LTS
OS type: 64-bit
Gnome version 42.4
Windowing system: Wayland
---


Also no other game opens either. Just wanted to point that out. Not one single game, ive checked Nekopara vol 1 and 2, Mirror and Sekiro, none of them got past that mini steam window saying opening.

**Comment by kisak-valve** [comment]
Hello @DuckEater54, a header only Proton log hints that you've encountered an issue before the actual game got a chance to start.

If you completely close Steam, then run `steam` from a terminal, are there any hints when you tell Steam to start the game?

Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by DuckEater54** [comment]
@kisak-valve i just copied the entire thing here: https://gist.github.com/DuckEater54/5151aadafb8ce57126f5d82b2165e9f9

**Comment by DuckEater54** [comment]
This is the full log from steam being ensured to not run up until vulkan shader processing crashes @kisak-valve 
the word user is just my name but replace-all

```
user@user-HP-Laptop-15s-du3xxx:~$ killall steam
steam: no process found
user@user-HP-Laptop-15s-du3xxx:~$ steam steam://rungameid/814380
steam.sh[58876]: Running Steam on ubuntu 22.04 64-bit
steam.sh[58876]: STEAM_RUNTIME is enabled automatically
setup.sh[59008]: Steam runtime environment up-to-date!
steam.sh[58876]: Steam client's requirements are satisfied
[2022-10-05 00:37:02] Startup - updater built Sep 28 2022 00:52:20
[2022-10-05 00:37:02] Startup - Steam Client launched with: '/home/user/.local/share/Steam/ubuntu12_32/steam' 'steam://rungameid/814380'
Installing breakpad exception handler for appid(steam)/version(1664418568)
[2022-10-05 00:37:02] Loading cached metrics from disk (/home/user/.local/share/Steam/package/steam_client_metrics.bin)
[2022-10-05 00:37:02] Using the following download hosts for Public, Realm steamglobal
[2022-10-05 00:37:02] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-10-05 00:37:02] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-10-05 00:37:02] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1664418568)
[2022-10-05 00:37:02] Verifying installation...
[2022-10-05 00:37:03] Verification complete
Loaded SDL version 2.25.0-7511446
Gtk-Message: 00:37:03.147: Failed to load module "gail"
Gtk-Message: 00:37:03.147: Failed to load module "atk-bridge"

(steam:59087): Gtk-WARNING **: 00:37:03.149: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:59087): Gtk-WARNING **: 00:37:03.151: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
steamwebhelper.sh[59110]: Runtime for steamwebhelper: defaulting to /home/user/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[59110]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Installing breakpad exception handler for appid(steam)/version(1664418568)
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
CAppInfoCacheReadFromDiskThread took 44 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Could not connect to X session manager: None of the authentication protocols specified are supported

(steam:59087): GLib-CRITICAL **: 00:37:03.613: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:59087): GLib-CRITICAL **: 00:37:03.613: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
Could not connect to X session manager: None of the authentication protocols specified are supported

(steam:59087): Gtk-WARNING **: 00:37:03.785: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1664418568)
Message type 9806 wasn't declared, but we registered job CClientJobEnableOrDisableDownloads to handle it?
Installing breakpad exception handler for appid(steam)/version(1664418568)
local (potentially out of sync) copy of roaming config loaded - 530 bytes.
Installing breakpad exception handler for appid(steam)/version(1664418568)
roaming config store loaded successfully - 530 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 10ms
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1664418568)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Failed to init SteamVR because it isn't installed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
ExecCommandLine: "'/home/user/.local/share/Steam/ubuntu12_32/steam' 'steam://rungameid/814380'"
ExecuteSteamURL: "steam://rungameid/814380"
System startup time: 4.72 seconds
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
BuildCompleteAppOverviewChange: 271
RegisterForAppOverview 1: 12ms
RegisterForAppOverview 2: 12ms
Proton: Upgrading prefix from None to 7.0-100 (/media/user/disk/SteamLibrary/steamapps/compatdata/814380/)
Traceback (most recent call last):
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1508, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1303, in init_session
    g_compatdata.setup_prefix()
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 781, in setup_prefix
    self.migrate_user_paths()
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 759, in migrate_user_paths
    os.symlink(src=link, dst=old)
PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '/media/user/disk/SteamLibrary/steamapps/compatdata/814380/pfx/drive_c/users/steamuser/Local Settings/Application Data'
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
Fossilize INFO: Setting autogroup scheduling.
Installing breakpad exception handler for appid(steam)/version(1664418568)
Installing breakpad exception handler for appid(steam)/version(1664418568)
Fossilize INFO: Setting autogroup scheduling.
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 814380, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 814380, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/user/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=814380 -- /home/user/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/user/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/user/disk/SteamLibrary/steamapps/common/Sekiro/sekiro.exe'\0
Game process added : AppID 814380 "/home/user/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=814380 -- /home/user/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/user/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/user/disk/SteamLibrary/steamapps/common/Sekiro/sekiro.exe'", ProcID 59548, IP 0.0.0.0:0
chdir /media/user/disk/SteamLibrary/steamapps/common/Sekiro
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 59553 != 59550, skipping destruction (fork without exec?)
GameAction [AppID 814380, ActionID 1] : LaunchApp changed task to Completed with ""
Proton: Upgrading prefix from None to 7.0-100 (/media/user/disk/SteamLibrary/steamapps/compatdata/814380/)
Traceback (most recent call last):
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1508, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1303, in init_session
    g_compatdata.setup_prefix()
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 781, in setup_prefix
    self.migrate_user_paths()
  File "/home/user/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 759, in migrate_user_paths
    os.symlink(src=link, dst=old)
PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '/media/user/disk/SteamLibrary/steamapps/compatdata/814380/pfx/drive_c/users/steamuser/Local Settings/Application Data'
Game process removed: AppID 814380 "/home/user/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=814380 -- /home/user/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/user/.local/share/Steam/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/user/disk/SteamLibrary/steamapps/common/Sekiro/sekiro.exe'", ProcID 59548 
ThreadGetProcessExitCode: no such process 59657
ThreadGetProcessExitCode: no such process 59656
ThreadGetProcessExitCode: no such process 59655
ThreadGetProcessExitCode: no such process 59551
ThreadGetProcessExitCode: no such process 59550
ThreadGetProcessExitCode: no such process 59549
Uploaded AppInterfaceStats to Steam
```

**Comment by kisak-valve** [comment]
Thanks, this is the line of importance: `PermissionError: [Errno 1] Operation not permitted: '../AppData/Local' -> '/media/user/disk/SteamLibrary/steamapps/compatdata/814380/pfx/drive_c/users/steamuser/Local Settings/Application Data'`

**Comment by kisak-valve** [comment]
What filesystem are you using with `/media/<user>/disk/`?

**Comment by DuckEater54** [comment]
> What filesystem are you using with `/media/<user>/disk/`?

According to windows explorer -> local disk (E;) Properties -> File system, it is exFAT. I am currently using that disk on my windows laptop right now for something and its a USB hard drive

**Comment by kisak-valve** [comment]
Thanks, that's a key detail. exFAT is currently incompatible with Proton, but there's a feature request to look into improving that at #3835. The general recommendation is to use a Linux native filesystem instead.

It should also be noted that sharing a Steam Library between OSes is not supported and unexpected/undefined behavior might occur, but that's not directly related to this issue report. (https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation)

**Comment by DuckEater54** [comment]
> It should also be noted that sharing a Steam Library between OSes is not supported and unexpected/undefined behavior might occur, but that's not directly related to this issue report

Yeah I know it would turn out weird. I don't intend to do it this way sine I'm putting all the games i can't run on my windows laptop onto this USB to run on my Ubuntu laptop with proton
