### ISSUE TITLE
Phantom Doctrine (559100)

### ISSUE THREAD

**Issue by julienbenjamin** [ValveSoftware/Proton#7134]
# Compatibility Report
- Name of the game with compatibility issues: Phantom Doctrine
- Steam AppID of the game: 559100

## System Information
- GPU: AMD RX6600XT
- Video driver version: Mesa 23.1.7-1
- Kernel version: 6.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/julienbenjamin/335d67979a4d295cceb023ecc899742f
- Proton version: Proton Experimental/8.0-3/7.0-6 + GE-Proton 8-13/7-16

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 `PROTON_LOG=1 %command%`  output:
```
======================
Proton: 1689631677 proton-8.0-3c
SteamGameId: 559100
Command: ['/data/SteamLibrary/steamapps/common/PhantomDoctrine/IWTB.exe', '-Installed']
Options: {'forcelgadd'}
depot: 0.20230905.59202
pressure-vessel: 0.20230905.0 scout
scripts: 0.20230905.0
sniper: 0.20230905.59202 sniper 0.20230905.59202
Kernel: Linux 6.4.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.13-1 (2023-08-31) x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
======================
```

## Symptoms

Game does not start.

I know it used to before, back in 2018. There was some ESync-related issues before at that time, which required the game from being launched with the NO_ESYNC argument.

I tried several Proton versions ; none allowed it to launch.

## Reproduction

Try to run it through Steam (Clicking "Play" on the game library page).

**Comment by kisak-valve** [comment]
Hello @julienbenjamin, a header only Proton log hints that something went wrong before the game itself had a chance to start. If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew when you tell Steam to start the game? (Debian's Steam package might divert the terminal spew to a file.)

Also, what filesystem are you using with `/data/SteamLibrary/`?

**Comment by julienbenjamin** [comment]
> Hello @julienbenjamin, a header only Proton log hints that something went wrong before the game itself had a chance to start. If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew when you tell Steam to start the game? (Debian's Steam package might divert the terminal spew to a file.)

I should have led with that, indeed, `steam` is indeed the one from Debian repositories. However, I do not have any issue with any other game like this (and to be frank, the empty log left me puzzled).

I had also missed the following error when running it from the CLI: 

```
Proton: Upgrading prefix from None to 8.0-103 (/data/SteamLibrary/steamapps/compatdata/559100/)
Traceback (most recent call last):
  File "/data/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1658, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/data/SteamLibrary/steamapps/common/Proton 8.0/proton", line 1453, in init_session
    g_compatdata.setup_prefix()
  File "/data/SteamLibrary/steamapps/common/Proton 8.0/proton", line 789, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/data/SteamLibrary/steamapps/compatdata/559100/pfx//dosdevices/c:'
```
Seeing this, I figured my `pfx` folder was also from back then, so I deleted it and it worked. I feel quite silly opening this issue, now since it was a quite trivial issue. Especially since it was something you had to often in the past, but I guess I've lost the habit.

> Also, what filesystem are you using with `/data/SteamLibrary/`?

I should have clarified that point, it is `ext4`. So, no NTFS-related issue then ;)

Anyway, sorry for the inconvenience.

**Comment by ipr** [comment]
For me, game does start but after intro video (after creating character) I'm stuck in a black screen with Proton experimental and with 8.0-3.

Log shows:
285422.481:013c:0140:warn:seh:OutputDebugStringA "[2023.09.26-21.44.44:864][843]LogMoviePlayer: Shutting down movie player\r\n"
285422.481:013c:0140:trace:seh:dispatch_exception code=40010006 flags=0 addr=000000007B00CD97 ip=7b00cd97
285422.481:013c:0140:trace:seh:dispatch_exception  info[0]=000000000000004b
285422.481:013c:0140:trace:seh:dispatch_exception  info[1]=000000000074d6a0
285422.481:013c:0140:warn:seh:dispatch_exception "[2023.09.26-21.44.44:864][843]LogMoviePlayer: Shutting down movie player\r\n"

285422.482:013c:0140:trace:seh:RtlRestoreContext returning to 000000007B00E92A stack 00000000004EC7B0
285422.596:013c:0324:fixme:mfplat:topology_loader_Load iface 000000002C8732A0, input_topology 00000000023D1940, ret_topology 000000002873FCE8, current_topology 0000000000000000 stub!
285422.601:013c:0324:fixme:mfplat:media_source_QueryInterface {6ef2a662-47c0-4666-b13d-cbb717f2fa2c}, 000000002873FBC8.

285562.439:013c:0140:err:sync:RtlpWaitForCriticalSection section 0000000002376F10 "../src-wine/dlls/winegstreamer/media_source.c: cs" wait timed out in thread 0140, blocked by 03f8, retrying (60 sec)
285562.442:013c:0300:err:sync:RtlpWaitForCriticalSection section 0000000026E9DC78 (null) wait timed out in thread 0300, blocked by 0140, retrying (60 sec)

Skipping the cinematic will proceed to tutorial.

**Comment by julienbenjamin** [comment]
Came here to comment about this. With the same version of Proton (8.0-3), every video can crash the game (or rather Wine apparently) if you watch it to the end. The workaround is to skip it.


Here is an example of log during a game where I reach to a new cutscene: [steam-559100.zip](https://github.com/ValveSoftware/Proton/files/12743673/steam-559100.zip)

**Comment by frozen-sea** [comment]
Proton 8 freezes consistently at the end of the intro video (Phantom Doctrine logo, right before main menu). Works fine on both Proton 7 and Experimental bleeding-edge though. No immediate issues when actually in menus or playing missions.

* 4070 Ti, driver 535.104.05
* Kernel 6.5.5

**Comment by kisak-valve** [comment]
Hello @frozen-sea, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by frozen-sea** [comment]
> Hello @frozen-sea, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put them in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Here you go.

[steam-559100.log](https://github.com/ValveSoftware/Proton/files/12774033/steam-559100.log)
https://gist.github.com/frozen-sea/768dedd0590df05184f7d5263654e142
