### ISSUE TITLE
Proton 8+ hangs during update

### ISSUE THREAD

**Issue by KenSharp** [ValveSoftware/Proton#7187]
#### Your system information

* Steam client version (build number or date): updater built May 30 2023 20:40:12 ? (because of bug ValveSoftware/steam-for-linux#9851)
* Distribution (e.g. Ubuntu): Ubuntu Jammy
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13061675/steam-logs.tar.gz)
* GPU: Nvidia GK104GL [Quadro K5000]

#### Please describe your issue in as much detail as possible:
Proton 8 (and Experimental) never finishes installing/updating the Wineprefix. It seems to be waiting for some futex.

![proton](https://github.com/ValveSoftware/steam-for-linux/assets/13607576/fbfbe9ea-8724-4f74-94b5-2f1ded7bde64)

The process has to be killed which obviously results in nothing good happening.

```
wine: configuration in L"/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/files/share/default_pfx" has been updated.
pid 54400 != 54398, skipping destruction (fork without exec?)
Traceback (most recent call last):
  File "/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1714, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1506, in init_session
    g_compatdata.setup_prefix()
  File "/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 910, in setup_prefix
    try_copy(g_proton.default_pfx_dir + "drive_c/openxr/wineopenxr64.json", "drive_c/openxr",
  File "/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 163, in try_copy
    copyfile(src, dst)
  File "/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 225, in copyfile_reflink
    with open(srcname, 'rb', buffering=0) as src:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ken/.local/share/Steam/steamapps/common/Proton - Experimental/files/share/default_pfx/drive_c/openxr/wineopenxr64.json'
```

#### Steps for reproducing this issue:

1. Change the Proton used to 8 or Experimental.
2. Run any game that depends on it.

Proton 7 seems fine.

**Comment by KenSharp** [comment]
Possibly the same as [#9355](https://github.com/ValveSoftware/steam-for-linux/issues/9355)

**Comment by KenSharp** [comment]
Given the two horrendous bugs I'm leaving this here to remind me for the future:

When installing a new Windows game I need to manually add an entry `~/.local/share/Steam/config/config.vdf` in the form

```
					"numeric_game_id"
					{
						"name"		"proton_7"
						"config"		""
						"priority"		"250"
					}
```

And this is **not** JSON.

**Comment by KenSharp** [comment]
Looks okay now. Proton 8, 9 and "Experimental" seem to complete the updates without issue. Will of course shout if it does come back and I was just lucky.
