### ISSUE TITLE
Game doesn't start when installed on NTFS (ntfs3) disk

### ISSUE THREAD

**Issue by Samega7Cattac** [ValveSoftware/Proton#7215]
#### Your system information

* Steam client version (build number or date): 1698260427
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13200373/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I have a m.2 disk that is shared on my dualboot system (with Windows) so I made it NTFS (the new ntfs3 driver, not ntfs-3g) since it should work according with [this guide](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows) from proton.
But every game I install on it, when I press "Play" it seems to run for a few seconds and just closes (the game doesn't start).
If i try to install on the same disk with my system (in btrfs) it works.
This is my line on `/etc/fstab`: `UUID=4**************C    /run/media/samega7cattac/Data    ntfs    uid=1000,gid=1000,rw,user,exec,umask=000    0 0`

#### Steps for reproducing this issue:

1. Format a disk in NTFS
2. Set `fstab` like in the guide
3. Install a game in that disk.
4. Try to launch it

**Comment by Samega7Cattac** [comment]
Here's the log from trying to open a game:
[steam-291550.log](https://github.com/ValveSoftware/steam-for-linux/files/13200379/steam-291550.log)

**Comment by kisak-valve** [comment]
Hello @Samega7Cattac, Proton interacting with NTFS is known to be finicky and the general recommendation is to use a Linux native filesystem with it. Blind guess that the default wineprefix is damaged from Proton being installed on a NTFS formatted Steam library folder.

**Comment by Samega7Cattac** [comment]
Is there any filesystem that would work on Linux and Windows?
Bc I have steam installed on both and the steam library using the same disk (different folders).

**Comment by kisak-valve** [comment]
Some people have suggested BTRFS for Windows.

**Comment by dreampiggy** [comment]
This issue catch me as well.

When moving the game from NTFS-based SD card into the built-in SteamOS ext4, the game works again.

The reason why use NTFS on SD card is because....I use Win-To-Go (require NTFS for Windows System...Suck)

I believe this issue has history been fixed in proton v7, but regression in v8 and experimental

**Comment by Samega7Cattac** [comment]
If it's a regression it should be considered a bug in proton 8 tho

**Comment by Samega7Cattac** [comment]
@kisak-valve I can now confirm it's a regression, everything works with proton 7.0-6
In case for more logs or anything else just ask

**Comment by LoneFenris** [comment]
Different log error to the above, but similar effect. Maybe different issue, though

```
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe38eb8f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe38ea1c0
CAppInfoCacheReadFromDiskThread took 289 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 285
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 210ms
BuildCompleteAppOverviewChange: 2266 apps
RegisterForAppOverview 1: 127ms
RegisterForAppOverview 2: 131ms
Proton: Upgrading prefix from None to 9.0-202 (/mnt/wally/SteamLinux/SteamLibrary/steamapps/compatdata/867290/)
Traceback (most recent call last):
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1599, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1506, in init_session
    g_compatdata.setup_prefix()
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 797, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/mnt/wally/SteamLinux/SteamLibrary/steamapps/compatdata/867290/pfx//dosdevices/c:'
chdir "/mnt/wally/SteamLinux/SteamLibrary/steamapps/common/Crossroads Inn"
ERROR: ld.so: object '/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 717 for gameID 867290
ERROR: ld.so: object '/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Proton: Upgrading prefix from None to 9.0-202 (/mnt/wally/SteamLinux/SteamLibrary/steamapps/compatdata/867290/)
Traceback (most recent call last):
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1599, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1506, in init_session
    g_compatdata.setup_prefix()
  File "/home/lonefenris/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 797, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
OSError: [Errno 22] Invalid argument: '../drive_c' -> '/mnt/wally/SteamLinux/SteamLibrary/steamapps/compatdata/867290/pfx//dosdevices/c:'
Uploaded AppInterfaceStats to Steam
Removing process 717 for gameID 867290
[2024-08-17 23:26:35] Background update loop checking for update. . .
[2024-08-17 23:26:35] Checking for available updates...
[2024-08-17 23:26:35] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=3903404967
[2024-08-17 23:26:35] Manifest download: send request
[2024-08-17 23:26:35] Manifest download: waiting for download to finish
[2024-08-17 23:26:36] Manifest download: finished
[2024-08-17 23:26:36] Download skipped: /steam_client_ubuntu12?t=3903404967 version 1721173382, installed version 1721173382, existing pending version 0
[2024-08-17 23:26:36] Nothing to do
```

This one is from Crossroads Inn and looks to me like an attempt to use a forbidden NTFS filename (colon is a reserved character in NTFS filenames). Works fine when installed on BTRFS.
