### ISSUE TITLE
Far Cry 2 (19900)

### ISSUE THREAD

**Issue by adrianlshaw** [ValveSoftware/Proton#775]
Works flawlessly. I must say I'm impressed with the Proton project so far, the general results have been nothing short of amazing.

Specs: Proton 3.7-3, Ubuntu 18.04, NVIDIA Corporation G94GL [Quadro FX 1800] (rev a1)
Full specs: https://gist.github.com/adrianlshaw/13b21eae4d9ad3c6c79474396110feed

**Comment by lineber** [comment]
I can confirm this. I just purchased the game and started the Story Mode, works great. Got to gameplay and it was as expected. Pretty decent for a 10-year-old game.
Specs;  Fedora 28, GTX 1060 (Nvidia drivers)
https://gist.github.com/lineber/9a75368b3e6dc1274dae29d98b1d7851

**Comment by buschmann23** [comment]
For me it does not work. Leafs of trees are big blocks as visible in the linked screenshot.

Screenshot: https://wolke.huessenbergnetz.de/index.php/s/RT4mPxmy3efyzGr

It also crashes on cut scenes, for example after arriving the city.

I also tried with low details and with the following startup parameters:
PROTON_USE_WINED3D11=1, PROTON_NO_D3D11=1 or PROTON_NO_ESYNC=1

My specs:
Distribution: openSUSE Tumbleweed
Linux: 4.18.5
GPU: AMD Radeon R9 280
GPU driver: amdgpu 18.0.1 / Mesa 18.1.6 / LLVM 6.0.1
GPU memory: 3072MB
CPU: AMD FX 6300
RAM: 16GB
Resolution: 1920x1080
Proton: 3.7-5 Beta

Fulls specs: https://gist.github.com/buschmann23/f0040553d4bc4bdeb567778bd52f7946

**Comment by shane-powell** [comment]
Not working for me.

Mouse issues in menu then crash to desktop after selecting character.

Ubuntu 18.04.1
Proton 3.7-3.
GTX 1060 6GB (Driver 396.54)


Specs https://gist.github.com/kenjara/b9aae11a5124fca193bbb6c7e5615ee8

**Comment by kapsh** [comment]
@buschmann23 I also see square trees like on your screenshot. Have you found solution so far?

System info: https://gist.github.com/kapsh/814e5da8e3078102b88b1488884e9410

**Comment by jacobc-eth** [comment]
Game is crashing for me whenever I try to create a new single player game, no error is given, it just abruptly crashes and disappears on during the Loading screen. On rare occassion I can get the game to play and then crash after a couple of minutes.

Manjaro 18
Proton 3.7-8 OR Proton 3.16-4
nVidia GTX 1080 ti (driver version 415)

[steam-19900.log](https://github.com/ValveSoftware/Proton/files/2752806/steam-19900.log)

**Comment by buschmann23** [comment]
@kapsh I currently can not even start it. I had removed it from the library and now reinstalled it by downloading it again.

After selecting “Play the game“ in the selector window nothing happens. On console I have the following output:

```
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 19900, ActionID 3] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 19900, ActionID 3] : LaunchApp continues with user response "0"
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
Traceback (most recent call last):
  File "/opt/Steam/SteamApps/steamapps/common/Proton 3.16 Beta/proton", line 309, in <module>
    shutil.copy(basedir + "/dist/lib/wine/dxvk/openvr_api_dxvk.dll", prefix + "/drive_c/windows/syswow64/")
  File "/usr/lib64/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/opt/Steam/SteamApps/steamapps/compatdata/19900/pfx//drive_c/windows/syswow64/'
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 19900
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 19900
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 19900, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 19900, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 19900 "", ProcID 5149, IP 0.0.0.0:0
ERROR: ld.so: object '/home/buschmann/Dokumente/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/buschmann/Dokumente/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/buschmann/Dokumente/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Traceback (most recent call last):
  File "/opt/Steam/SteamApps/steamapps/common/Proton 3.16 Beta/proton", line 309, in <module>
    shutil.copy(basedir + "/dist/lib/wine/dxvk/openvr_api_dxvk.dll", prefix + "/drive_c/windows/syswow64/")
  File "/usr/lib64/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/opt/Steam/SteamApps/steamapps/compatdata/19900/pfx//drive_c/windows/syswow64/'
>>> Adding process 5149 for game ID 19900
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 5154 for game ID 19900
GameAction [AppID 19900, ActionID 3] : LaunchApp changed task to Completed with ""
Traceback (most recent call last):
  File "/opt/Steam/SteamApps/steamapps/common/Proton 3.16 Beta/proton", line 309, in <module>
    shutil.copy(basedir + "/dist/lib/wine/dxvk/openvr_api_dxvk.dll", prefix + "/drive_c/windows/syswow64/")
  File "/usr/lib64/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/opt/Steam/SteamApps/steamapps/compatdata/19900/pfx//drive_c/windows/syswow64/'
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x1f4ff40
Serial number of failed request:  20456
xerror_handler: X failed, continuing
Game removed: AppID 19900 "", ProcID 5149 
No cached sticky mapping in ActivateActionSet.
```

This is on openSUSE Tumbleweed with python 3.6.5.

My current Steam system information:
https://gist.github.com/buschmann23/01d4f19b4ee3392a54724aaf1c899061

**Comment by kisak-valve** [comment]
Version 6.3.6 broke Far Cry 2 compatibility

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5100.
@halvors posted on 2021-08-21T12:56:05:

# Compatibility Report
- Name of the game with compatibility issues: Far Cry 2
- Steam AppID of the game: 19900

## System Information
- GPU: AMD RADV NAVI10
- Driver/LLVM version: amdgpu
- Kernel version: 5.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/halvors/0d67036c1b81f0e4c1e4cae583466262
- Proton version: 6.3.6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Far Cry 2 instantly crash on launch.

## Reproduction
Try to launch Far Cry 2.
[steam-19900.log](https://github.com/ValveSoftware/Proton/files/7025531/steam-19900.log)

**Comment by alasky17** [comment]
@halvors Could you try Far Cry 2 again with the new Proton 6.3-6c release?  I'm hoping that the fix for the prefix upgrades will fix this crash.

**Comment by halvors** [comment]
> @halvors Could you try Far Cry 2 again with the new Proton 6.3-6c release? I'm hoping that the fix for the prefix upgrades will fix this crash.

Sorry for late answer, can i somehow switch to 6.3-6c in steam?

**Comment by halvors** [comment]
I assume the 6.3-6 in steam is now actually 6.3-6c? Anyway it works now, thx :-)

**Comment by halvors** [comment]
Proton 7 breaks ingame map downloads both from HTTP and directly from host using TCP.
Could this somehow be related to missing permission to filesystem?
Is there any changes in Proton 7 that could have broken this?

Still works great on Proton 6.

**Comment by kisak-valve** [comment]
Hello @halvors, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by Tobe95** [comment]
Is anyone able to play the game in DX10 mode? Using Proton 7.0/8.0 on a fresh prefix but there's no option for D3D10 in the video settings:
![20230707205750_1](https://github.com/ValveSoftware/Proton/assets/70862046/48efc601-0746-4359-822b-1bfc8f5260dc)
This is with GE-Proton just for comparison (though the game crashes when actually attempting to render something) 
![20230707204523_1](https://github.com/ValveSoftware/Proton/assets/70862046/c7d6458a-66c6-4a8c-a405-17a3ec53f917)

**Edit:**

Under Proton Experimental, DX10 is available as an option as well, however the game crashes after the startup logo.

To reproduce: Launch the game with Proton Experimental. Under display options set DirectX Version from "9" to "10", save changes and close the game (restart required to apply changes). The game will crash on startup.

Steam OS 3.4.8 (Steam Deck) 
Proton Experimental (8.0-20230705b)

[steam-19900.log](https://github.com/ValveSoftware/Proton/files/11985914/steam-19900.log)

**Comment by CSahajdacny** [comment]
I think DX10 was blocked by the devs because it was broken beyond repair.

**Comment by Tobe95** [comment]
Are you sure about it being blocked? I know about some issues reported with DX10 mode for FC2, though I've been thinking DXVK might possibly alleviate these and provide overall better performance than default DX9.

There's lots of results when searching Google and people comparing  DX9 vs DX10, even for Fortune's Edition:
https://www.youtube.com/watch?v=jjzZrh6s02o

**Comment by Reidond** [comment]
Game crashes when launched. Tried GE-Proton8-24, Proton Experimental, Proton 8.0-4, Proton 7.0-6

Just loops with this error:
![image](https://github.com/ValveSoftware/Proton/assets/20406775/bbe6769a-664e-4850-b9c3-d828d10416c2)

Steam Deck (SteamOS 3.5.5)
[steam-19900.log](https://github.com/ValveSoftware/Proton/files/13404621/steam-19900.log)

**Comment by Reidond** [comment]
Cannot reproduce it on Steam Deck OLED SteamOS 3.5.7

**Comment by nyllewin** [comment]
> Game crashes when launched. Tried GE-Proton8-24, Proton Experimental, Proton 8.0-4, Proton 7.0-6
> 
> Just loops with this error: -- snip --
> 
> Steam Deck (SteamOS 3.5.5) [steam-19900.log](https://github.com/ValveSoftware/Proton/files/13404621/steam-19900.log)

hey, did you ever manage to get this running? Same Issue here and same unable to reproduce on steamdeck.
never mind, dug around and found the cpu topology posts, limiting to less than 32 cores seems to do it.

**Comment by Reidond** [comment]
forgot to post it but I don't have this issue anymore

**Comment by waspennator** [comment]
I dont have the game to check, but looking at pcgamingwiki and protondb, it seems like this game has issues unless you can the framerate to 60 with "DXVK_FRAME_RATE=60 %command%" like bouncing npcs above 60 fps

**Comment by waspennator** [comment]
Bought it and tried it, unsure if using that command actually fixes it tbh, sometimes it works, other times when I test it, it breaks (specifically the moment where you wake up in the hq after escaping or dying from the burning village

**Comment by simifor** [comment]
the game has the option to cap framerate to 60 fps in the video settings, is the dxvk framerate limit actually needed?

**Comment by waspennator** [comment]
> the game has the option to cap framerate to 60 fps in the video settings, is the dxvk framerate limit actually needed?

I was just going off what protondb posts recommended. Plus it seemed to be 50/50 when locking the framerate to 60 in options would have actually fix the hq softlock or not in the beginning
